///////////////////////////////////////////////////////////////////////////////
// Copyright © 2002, Open Design Alliance Inc. ("Open Design") 
// 
// This software is owned by Open Design, and may only be incorporated into 
// application programs owned by members of Open Design subject to a signed 
// Membership Agreement and Supplemental Software License Agreement with 
// Open Design. The structure and organization of this Software are the valuable 
// trade secrets of Open Design and its suppliers. The Software is also protected 
// by copyright law and international treaty provisions. You agree not to 
// modify, adapt, translate, reverse engineer, decompile, disassemble or 
// otherwise attempt to discover the source code of the Software. Application 
// programs incorporating this software must include the following statment 
// with their copyright notices:
//
//      DWGdirect © 2002 by Open Design Alliance Inc. All rights reserved. 
//
// By use of this software, you acknowledge and accept the terms of this 
// agreement.
///////////////////////////////////////////////////////////////////////////////



#ifndef __ODDRAWABLE_H__
#define __ODDRAWABLE_H__

#include "RxObject.h"

class OdGiDrawableTraits;
class OdGiWorldDraw;
class OdGiViewportDraw;
class OdGsNode;
class OdDbStub;
class OdGeExtents3d;

#include "DD_PackPush.h"

/** Description:
    Interface that must be implemented by all graphical objects.  Objects that implmement this
    interface are capable of vectorizing themselves within the DWGdirect framework.

    {group:OdGi_Classes} 
*/
class FIRSTDLL_EXPORT OdGiDrawable : public OdRxObject
{
protected:
  OdGiDrawable();
public:

  ODRX_DECLARE_MEMBERS(OdGiDrawable);

  enum SetAttributesFlags
  {
    /** Description:
        Default flags, which indicate that the drawable objects uses only Gi primitives 
        and no nested calls to draw().
    */
    kDrawableNone                         = 0,

    /** Description:
        Classes derived from OdDbEntity should return this flag
        (the default implementation of OdDbEntity::setAttributes() sets this flag).
    */
    kDrawableIsAnEntity                   = 1,

    /** Description:
        The current drawable object uses nesting, but does use additional graphical primitives such
        as circle or shell (for example, OdDbBlockTableRecord::setAttributes returns this flag).
    */
    kDrawableUsesNesting                  = 2,

    /** Description:
        Indicates that this object should be treated like a block
        (for example, OdDbLeader::setAttributes returns this flag).                
    */
    kDrawableIsCompoundObject             = 4,

    /** Description:
        Currently not supported.        
    */
    kDrawableViewIndependentViewportDraw  = 8,

    /** Description:
        Indicates that the current object is invisible, and should not be rendered. 
        OdDbEntity::setAttributes checks the visibility of an entity, 
        and sets this flag if necessary.  Subsequent calls to worldDraw() and viewportDraw()
        may be skipped if this flag is returned for an object.
    */
    kDrawableIsInvisible                  = 16,

    /** Description:
        Currently not supported.  
    */
    kDrawableHasAttributes                = 32,

    /** Description:
        Currently not supported.
    */
    kDrawableRegenTypeDependantGeometry   = 64,

    /** Description:
        Indicates that the current object is a dimension
        (OdDbDimension returns this flag).
    */
    kDrawableIsDimension =(kDrawableIsAnEntity + kDrawableIsCompoundObject + 128),

    /** Description:
        Currently not supported.
    */
    kDrawableRegenDraw                    = 256,

    kLastFlag                             = kDrawableRegenDraw
  };

  /** Description:
      Sets the vectorization attributes for this object.  

      Arguments:
        pTraits (O) Pointer to object in which the attributes are to be set.

      Return Value:
      Attribute flags.

      Remarks:
      This function is called by the vectorization
      framework to set the attributes for an object, prior to calling worldDraw() or
      viewportDraw().
      
      See Also:
      
        o SetAttributesFlags 
  */
  virtual OdUInt32 setAttributes(OdGiDrawableTraits* traits) const = 0;

  /** Description:
      Creates a geometric representation of this entity that is independent of the view direction.

      Arguments:
      pWd (I/O) Context which receives the geometric and attribute information
        generated by this entity.

      Return Value:
      true if the geometric representation can be generated in a
      view-independent manner, otherwise false (indicating that viewportDraw must be called).
  */
  virtual bool worldDraw(OdGiWorldDraw* wd) const = 0;

  /** Description:
      Creates a geometric representation of this entity that is dependent on the view direction.

      Remarks:
      This function is called once per view.

      Arguments:
      pWd (I/O) Context which receives the geometric and attribute information
        generated by this entity.
  */
  virtual void viewportDraw(OdGiViewportDraw* vd) const = 0;

  /** Description:
      Returns true if this object is database-resident, false otherwise.
  */
  virtual bool isPersistent() const = 0;

  /** Returns the database ID of this object (if it is persistent), otherwise returns
      a NULL pointer.
  */
  virtual OdDbStub* id() const = 0;

  /** Description:
      Sets the node that is associated with this drawable object.  An OdGsNode can be used
      for entity level caching of vectorization data.
  */
	virtual void setGsNode(OdGsNode* gsnode) = 0;

  /** Description:
      Returns the node that is associated with this drawable object.  An OdGsNode can be used
      for entity level caching of vectorization data.
  */
	virtual OdGsNode* gsNode() const = 0;

  virtual OdUInt32 viewportDrawLogicalFlags(OdGiViewportDraw* ) const;

 /** Description:
      Returns a WCS bounding box that represents the extents for this entity.

      Arguments:
      extents (O) Receives the WCS extents.

      Return Value:
      eOk if the extents were calculated successfully, otherwise an
      appropriate error value.
  */
  virtual OdResult getGeomExtents(OdGeExtents3d& extents) const;
};

typedef OdSmartPtr<OdGiDrawable> OdGiDrawablePtr;

#include "DD_PackPop.h"

#endif // __ODDRAWABLE_H__


