// DWG header search structs -- automatically generated -- do not edit
// Copyright (c) 1999, Visio Corporation.  All rights reserved.

#ifndef _INC_HEADER_SEARCH_H
#define _INC_HEADER_SEARCH_H

struct headershortsearchstru headershortsearchdata[]=
	{
	{ "ACISOUTVER",			&db_header::SetAcisoutver,		&db_header::RetAcisoutver 		,true,	true,  true,  16,  120 },
	{ "AFLAGS",				&db_header::SetAflags,			&db_header::RetAflags 			,true,	true,  false,	0,	15 },
	{ "ANGDIR",				&db_header::SetAngdir,			&db_header::RetAngdir 			,true,	true,  false,	0,	 1 },
	{ "ATTMODE",			&db_header::SetAttmode,			&db_header::RetAttmode 			,true,	true,  false,	0,	 2 },
	{ "ATTREQ",				&db_header::SetAttreq,			&db_header::RetAttreq 			,true,	true,  false,	0,	 1 },
	{ "AUNITS",				&db_header::SetAunits,			&db_header::RetAunits 			,true,	true,  false,	0,	 4 },
	{ "AUPREC",				&db_header::SetAuprec,			&db_header::RetAuprec 			,true,	true,  false,	0,	 8 },
	{ "AXISMODE",			&db_header::SetAxismode,		&db_header::RetAxismode 		,true,	true,  false,	0,	 1 },
	{ "BLIPMODE",			&db_header::SetBlipmode,		&db_header::RetBlipmode 		,true,	true,  false,	0,	 1 },
	{ "CHAMMODE",			&db_header::SetChammode,		&db_header::RetChammode 		,true,	true,  false,	0,	 1 },
	{ "CMDACTIVE",			&db_header::SetCmdactive,		&db_header::RetCmdactive 		,false, false, false,  0,	0 },
	{ "CMDECHO",			&db_header::SetCmdecho,			&db_header::RetCmdecho 			,true,	true,  false,	0,	 1 },
	{ "CMLJUST",			&db_header::SetCmljust,			&db_header::RetCmljust 			,true,	true,  false,	0,	 2 },
	{ "COORDS",				&db_header::SetCoords,			&db_header::RetCoords 			,true,	true,  false,	0,	 2 },
	{ "CVPORT",				&db_header::SetCvport,			&db_header::RetCvport 			,true,	false, false,	1,	 0 },
	{ "CYCLECURR",			&db_header::SetCyclecurr,		&db_header::RetCyclecurr 		,false, false, false,  0,	0 },
	{ "CYCLEKEEP",			&db_header::SetCyclekeep,		&db_header::RetCyclekeep 		,false, false, false,  0,	0 },
	{ "DBMOD",				&db_header::SetDbmod,			&db_header::RetDbmod 			,false, false, false,  0,	0 },
	{ "DELOBJ",				&db_header::SetDelobj,			&db_header::RetDelobj 			,true,	true,  false,	0,	 1 },
	{ "DIASTAT",			&db_header::SetDiastat,			&db_header::RetDiastat 			,true,	true,  false,	0,	 1 },
	{ "DIMADEC",			&db_header::SetDimadec,			&db_header::RetDimadec 			,true,	true,  false,	-1,	 8 }, // EBATECH(CNBR) Bugzilla#78443 2003/2/8
	{ "DIMALT",				&db_header::SetDimalt,			&db_header::RetDimalt 			,true,	true,  false,	0,	 1 },
	{ "DIMALTD",			&db_header::SetDimaltd,			&db_header::RetDimaltd 			,true,	true,  false,	0,	 8 },
	{ "DIMALTTD",			&db_header::SetDimalttd,		&db_header::RetDimalttd 		,true,	true,  false,	0,	 8 },
	{ "DIMALTTZ",			&db_header::SetDimalttz,		&db_header::RetDimalttz 		,true,	true,  false,	0,	15 },
	{ "DIMALTU",			&db_header::SetDimaltu,			&db_header::RetDimaltu 			,true,	true,  false,	1,	 8 },
	{ "DIMALTZ",			&db_header::SetDimaltz,			&db_header::RetDimaltz 			,true,	true,  false,	0,	15 },
	{ "DIMASO",				&db_header::SetDimaso,			&db_header::RetDimaso 			,true,	true,  false,	0,	 1 },
	{ "DIMAUNIT",			&db_header::SetDimaunit,		&db_header::RetDimaunit 		,true,	true,  false,	0,	 4 },
	{ "DIMAZIN",			&db_header::SetDimazin,			&db_header::RetDimazin 			,true,	true,  false,	0,	 3 }, // EBATECH(CNBR) Bugzilla#78443 2003/2/8

	{ "DIMCLRD",			&db_header::SetDimclrd,			&db_header::RetDimclrd 			,true,	true,  false,	0, 256 },
	{ "DIMCLRE",			&db_header::SetDimclre,			&db_header::RetDimclre 			,true,	true,  false,	0, 256 },
	{ "DIMCLRT",			&db_header::SetDimclrt,			&db_header::RetDimclrt 			,true,	true,  false,	0, 256 },
	{ "DIMDEC",				&db_header::SetDimdec,			&db_header::RetDimdec 			,true,	true,  false,	0,	 8 },
	{ "DIMFIT",				&db_header::SetDimfit,			&db_header::RetDimfit 			,true,	true,  false,	0,	 5 },
	{ "DIMJUST",			&db_header::SetDimjust,			&db_header::RetDimjust 			,true,	true,  false,	0,	 4 },
	{ "DIMLIM",				&db_header::SetDimlim,			&db_header::RetDimlim 			,true,	true,  false,	0,	 1 },
	{ "DIMSAH",				&db_header::SetDimsah,			&db_header::RetDimsah 			,true,	true,  false,	0,	 1 },
	{ "DIMSD1",				&db_header::SetDimsd1,			&db_header::RetDimsd1 			,true,	true,  false,	0,	 1 },
	{ "DIMSD2",				&db_header::SetDimsd2,			&db_header::RetDimsd2 			,true,	true,  false,	0,	 1 },
	{ "DIMSE1",				&db_header::SetDimse1,			&db_header::RetDimse1 			,true,	true,  false,	0,	 1 },
	{ "DIMSE2",				&db_header::SetDimse2,			&db_header::RetDimse2 			,true,	true,  false,	0,	 1 },
	{ "DIMSHO",				&db_header::SetDimsho,			&db_header::RetDimsho 			,true,	true,  false,	0,	 1 },
	{ "DIMSOXD",			&db_header::SetDimsoxd,			&db_header::RetDimsoxd 			,true,	true,  false,	0,	 1 },
	{ "DIMTAD",				&db_header::SetDimtad,			&db_header::RetDimtad 			,true,	true,  false,	0,	 3 },
	{ "DIMTDEC",			&db_header::SetDimtdec,			&db_header::RetDimtdec 			,true,	true,  false,	0,	 8 },
	{ "DIMTIH",				&db_header::SetDimtih,			&db_header::RetDimtih 			,true,	true,  false,	0,	 1 },
	{ "DIMTIX",				&db_header::SetDimtix,			&db_header::RetDimtix 			,true,	true,  false,	0,	 1 },
	{ "DIMTOFL",			&db_header::SetDimtofl,			&db_header::RetDimtofl 			,true,	true,  false,	0,	 1 },
	{ "DIMTOH",				&db_header::SetDimtoh,			&db_header::RetDimtoh 			,true,	true,  false,	0,	 1 },
	{ "DIMTOL",				&db_header::SetDimtol,			&db_header::RetDimtol 			,true,	true,  false,	0,	 1 },
	{ "DIMTOLJ",			&db_header::SetDimtolj,			&db_header::RetDimtolj 			,true,	true,  false,	0,	 2 },
	{ "DIMTZIN",			&db_header::SetDimtzin,			&db_header::RetDimtzin 			,true,	true,  false,	0,	15 },
	{ "DIMUNIT",			&db_header::SetDimunit,			&db_header::RetDimunit 			,true,	true,  false,	1,	 8 },
	{ "DIMUPT",				&db_header::SetDimupt,			&db_header::RetDimupt 			,true,	true,  false,	0,	 1 },
	{ "DIMZIN",				&db_header::SetDimzin,			&db_header::RetDimzin 			,true,	true,  false,	0,	15 },
	{ "DISPSILH",			&db_header::SetDispsilh,		&db_header::RetDispsilh 		,true,	true,  false,	0,	 1 },
	{ "DRAGMODE",			&db_header::SetDragmode,		&db_header::RetDragmode 		,true,	true,  false,	0,	 2 },
	{ "DWGTITLED",			&db_header::SetDwgtitled,		&db_header::RetDwgtitled 		,true,	true,  false,	0,	 1 },
	{ "EDGEMODE",			&db_header::SetEdgemode,		&db_header::RetEdgemode 		,true,	true,  false,	0,	 1 },
	{ "EXPLMODE",			&db_header::SetExplmode,		&db_header::RetExplmode 		,true,	true,  false,	0,	 1 },
	{ "FASTZOOM",			&db_header::SetFastzoom,		&db_header::RetFastzoom 		,false, false, false,  0,	0 },
	{ "FILLMODE",			&db_header::SetFillmode,		&db_header::RetFillmode 		,true,	true,  false,	0,	 1 },
	{ "FITTYPE",			&db_header::SetFittype,			&db_header::RetFittype 			,true,	true,  false,	2,	 3 },
	{ "FLATLAND",			&db_header::SetFlatland,		&db_header::RetFlatland 		,true,	true,  false,	0,	 1 },
	{ "GPSMODE",			&db_header::SetGpsmode,			&db_header::RetGpsmode 			,true,	true,  false,	0,	 1 },
	{ "GPSPAUSED",			&db_header::SetGpspaused,		&db_header::RetGpspaused 		,true,	true,  false,	0,	 1 },
	{ "GRIDMODE",			&db_header::SetGridmode,		&db_header::RetGridmode 		,true,	true,  false,	0,	 1 },
	{ "HANDLES",			&db_header::SetHandles,			&db_header::RetHandles 			,true,	true,  true,   0,	1 },
	{ "HIGHLIGHT",			&db_header::SetHighlight,		&db_header::RetHighlight 		,true,	true,  false,	0,	 1 },
	{ "HPBOUND",			&db_header::SetHpbound,			&db_header::RetHpbound 			,true,	true,  false,	0,	 1 },
	{ "HPDOUBLE",			&db_header::SetHpdouble,		&db_header::RetHpdouble 		,true,	true,  false,	0,	 1 },
	{ "HPSTYLE",			&db_header::SetHpstyle,			&db_header::RetHpstyle 			,true,	true,  false,	0,	 2 },
	{ "ISLASTCMDPT",		&db_header::SetIslastcmdpt,		&db_header::RetIslastcmdpt 		,true,	true,  false,	0,	 1 },
	{ "ISOLINES",			&db_header::SetIsolines,		&db_header::RetIsolines 		,true,	true,  false,	0, 2047 },
	{ "LIMCHECK",			&db_header::SetLimcheck,		&db_header::RetLimcheck 		,true,	true,  false,	0,	 1 },
	{ "LTSCLWBLK",			&db_header::SetLtsclwblk,		&db_header::RetLtsclwblk 		,true,	true,  false,	0,	 1 },
	{ "LUNITS",				&db_header::SetLunits,			&db_header::RetLunits 			,true,	true,  false,	1,	 5 },
	{ "LUPREC",				&db_header::SetLuprec,			&db_header::RetLuprec 			,true,	true,  false,	0,	 8 },
	{ "MAXACTVP",			&db_header::SetMaxactvp,		&db_header::RetMaxactvp 		,true,	true,  false,	2,	64 }, // Change range 2-48 to 2-64
	{ "MEASUREMENT",		&db_header::SetMeasurement,		&db_header::RetMeasurement 		,true,	true,  false,	0,	 1 },
	{ "MENUECHO",			&db_header::SetMenuecho,		&db_header::RetMenuecho 		,true,	true,  false,	0,	15 },
	{ "MIRRTEXT",			&db_header::SetMirrtext,		&db_header::RetMirrtext 		,true,	true,  false,	0,	 1 },
	{ "ORTHOMODE",			&db_header::SetOrthomode,		&db_header::RetOrthomode 		,true,	true,  false,	0,	 1 },
	{ "OSMODE",				&db_header::SetOsmode,			&db_header::RetOsmode 			,true,	true,  false,	0, 32767 },
	{ "PDMODE",				&db_header::SetPdmode,			&db_header::RetPdmode 			,true,	true,  false,	0, 100 },
	{ "PELLIPSE",			&db_header::SetPellipse,		&db_header::RetPellipse 		,true,	true,  false,	0,	 1 },
	{ "PICKSTYLE",			&db_header::SetPickstyle,		&db_header::RetPickstyle 		,true,	true,  false,	0,	 3 },
	{ "PLINEGEN",			&db_header::SetPlinegen,		&db_header::RetPlinegen 		,true,	true,  false,	0,	 1 },
	{ "POLYSIDES",			&db_header::SetPolysides,		&db_header::RetPolysides 		,true,	true,  false,	3, 1024 },
	{ "PROXYGRAPHICS",		&db_header::SetProxygraphics,	&db_header::RetProxygraphics 	,true,	true,  false,	0,	 1 },
	{ "PSLTSCALE",			&db_header::SetPsltscale,		&db_header::RetPsltscale 		,true,	true,  false,	0,	 1 },
	{ "P_LIMCHECK",			&db_header::SetP_limcheck,		&db_header::RetP_limcheck 		,true,	true,  true,   0,	1 },
	{ "QTEXTMODE",			&db_header::SetQtextmode,		&db_header::RetQtextmode 		,true,	true,  false,	0,	 1 },
	{ "REGENMODE",			&db_header::SetRegenmode,		&db_header::RetRegenmode 		,true,	true,  false,	0,	 1 },
	{ "SAVEIMAGES",			&db_header::SetSaveimages,		&db_header::RetSaveimages 		,true,	true,  false,	0,	 2 },
	{ "SHADEDGE",			&db_header::SetShadedge,		&db_header::RetShadedge 		,true,	true,  false,	0,	 3 },
	{ "SHADEDIF",			&db_header::SetShadedif,		&db_header::RetShadedif 		,true,	true,  false,	0, 100 },
	{ "SKPOLY",				&db_header::SetSkpoly,			&db_header::RetSkpoly 			,true,	true,  false,	0,	 1 },
	{ "SNAPISOPAIR",		&db_header::SetSnapisopair,		&db_header::RetSnapisopair 		,true,	true,  false,	0,	 2 },
	{ "SNAPMODE",			&db_header::SetSnapmode,		&db_header::RetSnapmode 		,true,	true,  false,	0,	 1 },
	{ "SNAPSTYL",			&db_header::SetSnapstyl,		&db_header::RetSnapstyl 		,true,	true,  false,	0,	 1 },
	{ "SPLFRAME",			&db_header::SetSplframe,		&db_header::RetSplframe 		,true,	true,  false,	0,	 1 },
	{ "SPLINESEGS",			&db_header::SetSplinesegs,		&db_header::RetSplinesegs 		,true,	true,  false, -32768, 32767 },
	{ "SPLINETYPE",			&db_header::SetSplinetype,		&db_header::RetSplinetype 		,true,	true,  false,	1,	20 },
	{ "SURFTAB1",			&db_header::SetSurftab1,		&db_header::RetSurftab1 		,true,	true,  false,	2, 32766 },
	{ "SURFTAB2",			&db_header::SetSurftab2,		&db_header::RetSurftab2 		,true,	true,  false,	2, 32766 },
	{ "SURFTYPE",			&db_header::SetSurftype,		&db_header::RetSurftype 		,false, false, false,  0,	0 },
	{ "SURFU",				&db_header::SetSurfu,			&db_header::RetSurfu 			,true,	true,  false,	2, 200 },
	{ "SURFV",				&db_header::SetSurfv,			&db_header::RetSurfv 			,true,	true,  false,	2, 200 },
	{ "TEXTQLTY",			&db_header::SetTextqlty,		&db_header::RetTextqlty 		,true,	true,  false,	0, 100 },
	{ "TILEMODE",			&db_header::SetTilemode,		&db_header::RetTilemode 		,true,	true,  false,	0,	 1 },
	{ "TREEDEPTH",			&db_header::SetTreedepth,		&db_header::RetTreedepth 		,true,	true,  false, -32768, 32767 },
	{ "TRIMMODE",			&db_header::SetTrimmode,		&db_header::RetTrimmode 		,true,	true,  false,	0,	 1 },
	{ "UCSFOLLOW",			&db_header::SetUcsfollow,		&db_header::RetUcsfollow 		,true,	true,  false,	0,	 1 },
	{ "UCSICON",			&db_header::SetUcsicon,			&db_header::RetUcsicon 			,true,	true,  false,	0,	 3 },
	{ "UNDOCTL",			&db_header::SetUndoctl,			&db_header::RetUndoctl 			,false, false, false,  0,	0 },
	{ "UNDOMARKS",			&db_header::SetUndomarks,		&db_header::RetUndomarks 		,true,	false, false,	0,	 0 },
	{ "UNITMODE",			&db_header::SetUnitmode,		&db_header::RetUnitmode 		,true,	true,  false,	0,	 1 },
	{ "USERI1",				&db_header::SetUseri1,			&db_header::RetUseri1 			,true,	true,  false, -32768, 32767 },
	{ "USERI2",				&db_header::SetUseri2,			&db_header::RetUseri2 			,true,	true,  false, -32768, 32767 },
	{ "USERI3",				&db_header::SetUseri3,			&db_header::RetUseri3 			,true,	true,  false, -32768, 32767 },
	{ "USERI4",				&db_header::SetUseri4,			&db_header::RetUseri4 			,true,	true,  false, -32768, 32767 },
	{ "USERI5",				&db_header::SetUseri5,			&db_header::RetUseri5 			,true,	true,  false, -32768, 32767 },
	{ "USRTIMER",			&db_header::SetUsrtimer,		&db_header::RetUsrtimer 		,true,	true,  false,	0,	 1 },
	{ "VIEWMODE",			&db_header::SetViewmode,		&db_header::RetViewmode 		,false, false, false,  0,	0 },
	{ "VISRETAIN",			&db_header::SetVisretain,		&db_header::RetVisretain 		,true,	true,  false,	0,	 1 },
	{ "WORLDUCS",			&db_header::SetWorlducs,		&db_header::RetWorlducs 		,true,	true,  false,	0,	 1 },
	{ "WORLDVIEW",			&db_header::SetWorldview,		&db_header::RetWorldview 		,true,	true,  false,	0,	 1 },
	{ "WRITESTAT",			&db_header::SetWritestat,		&db_header::RetWritestat 		,true,	true,  false,	0,	 1 },
	{ "ZOOMPERCENT",		&db_header::SetZoompercent,		&db_header::RetZoompercent 		,true,	true,  false,	1, 20000 },
	};

struct headerrealsearchstru headerrealsearchdata[]=
	{
	{ "ANGBASE",			&db_header::SetAngbase,			&db_header::RetAngbase 			,false, false, false,  0.000000, 0.000000 },
	{ "AREA",				&db_header::SetArea,			&db_header::RetArea 			,true,	false, false,	0.000000, 0.000000 },
	{ "BACKZ",				&db_header::SetBackz,			&db_header::RetBackz 			,false, false, false,  0.000000, 0.000000 },
	{ "CELTSCALE",			&db_header::SetCeltscale,		&db_header::RetCeltscale 		,true,	false, false,	0.000000, 0.000000 },
	{ "CHAMFERA",			&db_header::SetChamfera,		&db_header::RetChamfera 		,true,	false, false,	0.000000, 0.000000 },
	{ "CHAMFERB",			&db_header::SetChamferb,		&db_header::RetChamferb 		,true,	false, false,	0.000000, 0.000000 },
	{ "CHAMFERC",			&db_header::SetChamferc,		&db_header::RetChamferc 		,true,	false, false,	0.000000, 0.000000 },
	{ "CHAMFERD",			&db_header::SetChamferd,		&db_header::RetChamferd 		,true,	true,  false,	0.000000, 3.000000 },
	{ "CIRCLERAD",			&db_header::SetCirclerad,		&db_header::RetCirclerad 		,true,	false, false,	0.000000, 0.000000 },
	{ "CMLSCALE",			&db_header::SetCmlscale,		&db_header::RetCmlscale 		,false, false, false,  0.000000, 0.000000 },
	{ "DIMALTF",			&db_header::SetDimaltf,			&db_header::RetDimaltf 			,true,	false, false,	0.000000, 0.000000 },
	{ "DIMASZ",				&db_header::SetDimasz,			&db_header::RetDimasz 			,true,	false, false,	0.000000, 0.000000 },
	{ "DIMCEN",				&db_header::SetDimcen,			&db_header::RetDimcen 			,false, false, false,  0.000000, 0.000000 },
	{ "DIMDLE",				&db_header::SetDimdle,			&db_header::RetDimdle 			,true,	false, false,	0.000000, 0.000000 },
	{ "DIMDLI",				&db_header::SetDimdli,			&db_header::RetDimdli 			,true,	false, false,	0.000000, 0.000000 },
	{ "DIMEXE",				&db_header::SetDimexe,			&db_header::RetDimexe 			,true,	false, false,	0.000000, 0.000000 },
	{ "DIMEXO",				&db_header::SetDimexo,			&db_header::RetDimexo 			,true,	false, false,	0.000000, 0.000000 },
	{ "DIMGAP",				&db_header::SetDimgap,			&db_header::RetDimgap 			,false, false, false,  0.000000, 0.000000 },
	{ "DIMLFAC",			&db_header::SetDimlfac,			&db_header::RetDimlfac 			,false, false, false,  0.000000, 0.000000 },
	{ "DIMRND",				&db_header::SetDimrnd,			&db_header::RetDimrnd 			,true,	false, false,	0.000000, 0.000000 },
	{ "DIMSCALE",			&db_header::SetDimscale,		&db_header::RetDimscale 		,true,	false, false,	0.000000, 0.000000 },
	{ "DIMTFAC",			&db_header::SetDimtfac,			&db_header::RetDimtfac 			,true,	false, false,	0.000000, 0.000000 },
	{ "DIMTM",				&db_header::SetDimtm,			&db_header::RetDimtm 			,false, false, false,  0.000000, 0.000000 },
	{ "DIMTP",				&db_header::SetDimtp,			&db_header::RetDimtp 			,false, false, false,  0.000000, 0.000000 },
	{ "DIMTSZ",				&db_header::SetDimtsz,			&db_header::RetDimtsz 			,true,	false, false,	0.000000, 0.000000 },
	{ "DIMTVP",				&db_header::SetDimtvp,			&db_header::RetDimtvp 			,false, false, false,  0.000000, 0.000000 },
	{ "DIMTXT",				&db_header::SetDimtxt,			&db_header::RetDimtxt 			,true,	false, false,	0.000000, 0.000000 },
	{ "DISTANCE",			&db_header::SetDistance,		&db_header::RetDistance 		,true,	false, false,	0.000000, 0.000000 },
	{ "DONUTID",			&db_header::SetDonutid,			&db_header::RetDonutid 			,true,	false, false,	0.000000, 0.000000 },
	{ "DONUTOD",			&db_header::SetDonutod,			&db_header::RetDonutod 			,true,	false, false,	0.000000, 0.000000 },
	{ "ELEVATION",			&db_header::SetElevation,		&db_header::RetElevation 		,false, false, false,  0.000000, 0.000000 },
	{ "FACETRES",			&db_header::SetFacetres,		&db_header::RetFacetres 		,true,	true,  false,	0.010000, 10.000000 },
	{ "FILLETRAD",			&db_header::SetFilletrad,		&db_header::RetFilletrad 		,true,	false, false,	0.000000, 0.000000 },
	{ "FRONTZ",				&db_header::SetFrontz,			&db_header::RetFrontz 			,false, false, false,  0.000000, 0.000000 },
	{ "HPANG",				&db_header::SetHpang,			&db_header::RetHpang 			,false, false, false,  0.000000, 0.000000 },
	{ "HPSCALE",			&db_header::SetHpscale,			&db_header::RetHpscale 			,true,	false, false,	0.000000, 0.000000 },
	{ "HPSPACE",			&db_header::SetHpspace,			&db_header::RetHpspace 			,true,	false, false,	0.000000, 0.000000 },
	{ "LASTANGLE",			&db_header::SetLastangle,		&db_header::RetLastangle 		,false, false, false,  0.000000, 0.000000 },
	{ "LASTCMDANG",			&db_header::SetLastcmdang,		&db_header::RetLastcmdang 		,false, false, false,  0.000000, 0.000000 },
	{ "LENSLENGTH",			&db_header::SetLenslength,		&db_header::RetLenslength 		,false, false, false,  0.000000, 0.000000 },
	{ "LTSCALE",			&db_header::SetLtscale,			&db_header::RetLtscale 			,true,	false, false,	0.000000, 0.000000 },
	{ "OFFSETDIST",			&db_header::SetOffsetdist,		&db_header::RetOffsetdist 		,false, false, false,  0.000000, 0.000000 },
	{ "PDSIZE",				&db_header::SetPdsize,			&db_header::RetPdsize 			,false, false, false,  0.000000, 0.000000 },
	{ "PERIMETER",			&db_header::SetPerimeter,		&db_header::RetPerimeter 		,true,	false, false,	0.000000, 0.000000 },
	{ "PLINEWID",			&db_header::SetPlinewid,		&db_header::RetPlinewid 		,true,	false, false,	0.000000, 0.000000 },
	{ "P_ELEVATION",		&db_header::SetP_elevation,		&db_header::RetP_elevation 		,false, false, false,  0.000000, 0.000000 },
	{ "SKETCHINC",			&db_header::SetSketchinc,		&db_header::RetSketchinc 		,false, false, false,  0.000000, 0.000000 },
	{ "SNAPANG",			&db_header::SetSnapang,			&db_header::RetSnapang 			,false, false, false,  0.000000, 0.000000 },
	{ "TDCREATE",			&db_header::SetTdcreate,		&db_header::RetTdcreate 		,true,	true,  true,   2440000.000000, 2470000.000000 },
	{ "TDINDWG",			&db_header::SetTdindwg,			&db_header::RetTdindwg 			,false, false, false,  0.000000, 0.000000 },
	{ "TDUPDATE",			&db_header::SetTdupdate,		&db_header::RetTdupdate 		,true,	true,  true,   2440000.000000, 2470000.000000 },
	{ "TDUSRTIMER",			&db_header::SetTdusrtimer,		&db_header::RetTdusrtimer 		,false, false, false,  0.000000, 0.000000 },
	{ "TEXTANGLE",			&db_header::SetTextangle,		&db_header::RetTextangle 		,false, false, false,  0.000000, 0.000000 },
	{ "TEXTSIZE",			&db_header::SetTextsize,		&db_header::RetTextsize 		,true,	false, false,	0.000000, 0.000000 },
	{ "THICKNESS",			&db_header::SetThickness,		&db_header::RetThickness 		,false, false, false,  0.000000, 0.000000 },
	{ "TRACEWID",			&db_header::SetTracewid,		&db_header::RetTracewid 		,true,	false, false,	0.000000, 0.000000 },
	{ "USERR1",				&db_header::SetUserr1,			&db_header::RetUserr1 			,false, false, false,  0.000000, 0.000000 },
	{ "USERR2",				&db_header::SetUserr2,			&db_header::RetUserr2 			,false, false, false,  0.000000, 0.000000 },
	{ "USERR3",				&db_header::SetUserr3,			&db_header::RetUserr3 			,false, false, false,  0.000000, 0.000000 },
	{ "USERR4",				&db_header::SetUserr4,			&db_header::RetUserr4 			,false, false, false,  0.000000, 0.000000 },
	{ "USERR5",				&db_header::SetUserr5,			&db_header::RetUserr5 			,false, false, false,  0.000000, 0.000000 },
	{ "VIEWASPECT",			&db_header::SetViewaspect,		&db_header::RetViewaspect 		,false, false, false,  0.000000, 0.000000 },
	{ "VIEWSIZE",			&db_header::SetViewsize,		&db_header::RetViewsize 		,false, false, false,  0.000000, 0.000000 },
	{ "VIEWTWIST",			&db_header::SetViewtwist,		&db_header::RetViewtwist 		,false, false, false,  0.000000, 0.000000 },
	};

struct headerstringsearchstru headerstringsearchdata[]=
	{
	{ "CMDNAMES",			&db_header::SetCmdnames,		&db_header::RetCmdnames 		},
	{ "DIMAPOST",			&db_header::SetDimapost,		&db_header::RetDimapost 		},
	{ "DIMBLK",				&db_header::SetDimblk,			&db_header::RetDimblk 			},
	{ "DIMBLK1",			&db_header::SetDimblk1,			&db_header::RetDimblk1 			},
	{ "DIMBLK2",			&db_header::SetDimblk2,			&db_header::RetDimblk2 			},
	{ "DIMPOST",			&db_header::SetDimpost,			&db_header::RetDimpost 			},
	{ "GPSPLAYED",			&db_header::SetGpsplayed,		&db_header::RetGpsplayed 		},
	{ "HPNAME",				&db_header::SetHpname,			&db_header::RetHpname 			},
	{ "INSNAME",			&db_header::SetInsname,			&db_header::RetInsname 			},
	{ "MENUNAME",			&db_header::SetMenuname,		&db_header::RetMenuname 		},
	{ "SAVENAME",			&db_header::SetSavename,		&db_header::RetSavename 		},
	{ "SHPNAME",			&db_header::SetShpname,			&db_header::RetShpname 			},
	{ "USERS1",				&db_header::SetUsers1,			&db_header::RetUsers1 			},
	{ "USERS2",				&db_header::SetUsers2,			&db_header::RetUsers2 			},
	{ "USERS3",				&db_header::SetUsers3,			&db_header::RetUsers3 			},
	{ "USERS4",				&db_header::SetUsers4,			&db_header::RetUsers4 			},
	{ "USERS5",				&db_header::SetUsers5,			&db_header::RetUsers5 			},
	};

struct headerpointsearchstru headerpointsearchdata[]=
	{
	{ "AXISUNIT",			&db_header::SetAxisunit,		&db_header::GetAxisunit 		},
	{ "GRIDUNIT",			&db_header::SetGridunit,		&db_header::GetGridunit 		},
	{ "LIMMAX",				&db_header::SetLimmax,			&db_header::GetLimmax 			},
	{ "LIMMIN",				&db_header::SetLimmin,			&db_header::GetLimmin 			},
	{ "P_LIMMAX",			&db_header::SetP_limmax,		&db_header::GetP_limmax 		},
	{ "P_LIMMIN",			&db_header::SetP_limmin,		&db_header::GetP_limmin 		},
	{ "SNAPBASE",			&db_header::SetSnapbase,		&db_header::GetSnapbase 		},
	{ "SNAPUNIT",			&db_header::SetSnapunit,		&db_header::GetSnapunit 		},
	};

struct header3dpointsearchstru header3dpointsearchdata[]=
	{
	{ "EXTMAX",				&db_header::SetExtmax,			&db_header::GetExtmax 			},
	{ "EXTMIN",				&db_header::SetExtmin,			&db_header::GetExtmin 			},
	{ "GPSLASTPT",			&db_header::SetGpslastpt,		&db_header::GetGpslastpt 		},
	{ "INSBASE",			&db_header::SetInsbase,			&db_header::GetInsbase 			},
	{ "LASTCMDPT",			&db_header::SetLastcmdpt,		&db_header::GetLastcmdpt 		},
	{ "LASTPOINT",			&db_header::SetLastpoint,		&db_header::GetLastpoint 		},
	{ "P_EXTMAX",			&db_header::SetP_extmax,		&db_header::GetP_extmax 		},
	{ "P_EXTMIN",			&db_header::SetP_extmin,		&db_header::GetP_extmin 		},
	{ "P_INSBASE",			&db_header::SetP_insbase,		&db_header::GetP_insbase 		},
	{ "P_UCSORG",			&db_header::SetP_ucsorg,		&db_header::GetP_ucsorg 		},
	{ "P_UCSXDIR",			&db_header::SetP_ucsxdir,		&db_header::GetP_ucsxdir 		},
	{ "P_UCSYDIR",			&db_header::SetP_ucsydir,		&db_header::GetP_ucsydir 		},
	{ "TARGET",				&db_header::SetTarget,			&db_header::GetTarget 			},
	{ "UCSORG",				&db_header::SetUcsorg,			&db_header::GetUcsorg 			},
	{ "UCSXDIR",			&db_header::SetUcsxdir,			&db_header::GetUcsxdir 			},
	{ "UCSYDIR",			&db_header::SetUcsydir,			&db_header::GetUcsydir 			},
	{ "VIEWCTR",			&db_header::SetViewctr,			&db_header::GetViewctr 			},
	{ "VIEWDIR",			&db_header::SetViewdir,			&db_header::GetViewdir 			},
	{ "VSMAX",				&db_header::SetVsmax,			&db_header::GetVsmax 			},
	{ "VSMIN",				&db_header::SetVsmin,			&db_header::GetVsmin 			},
	};

struct headershtstrsearchstru headershtstrsearchdata[]=
	{
	{ "CECOLOR",			&db_header::SetCecolor,			&db_header::RetCecolor 			,false, false, false,  0,	0 },
	{ "DWGCODEPAGE",		&db_header::SetDwgcodepage,		&db_header::RetDwgcodepage 		,false, false, false,  0,	0 },
	};

struct headerhandlesearchstru headerhandlesearchdata[]=
	{
	{ "HANDSEED",			&db_header::SetHandseed,		&db_header::RetHandseed 		},
	};

struct headerhipsearchstru headerhipsearchdata[]=
	{
	{ "CELTYPE",			&db_header::SetCeltype,			&db_header::RetCeltype 			},
	{ "CLAYER",				&db_header::SetClayer,			&db_header::RetClayer 			},
	{ "CMLSTYLE",			&db_header::SetCmlstyle,		&db_header::RetCmlstyle 		},
	{ "DIMSTYLE",			&db_header::SetDimstyle,		&db_header::RetDimstyle 		},
	{ "DIMTXSTY",			&db_header::SetDimtxsty,		&db_header::RetDimtxsty 		},
	{ "P_UCSNAME",			&db_header::SetP_ucsname,		&db_header::RetP_ucsname 		},
	{ "TEXTSTYLE",			&db_header::SetTextstyle,		&db_header::RetTextstyle 		},
	{ "UCSNAME",			&db_header::SetUcsname,			&db_header::RetUcsname 			},
	};

#endif
