// DWG header constructor/destructor -- automatically generated -- do not edit
// Copyright (c) 1999, Visio Corporation.  All rights reserved.

#include "db.h"
#include "header.h"
db_header::db_header(void)
	{
	acisoutver		= 120;
	aflags			= 0;
	angbase			= 0;
	angdir			= 0;
	area			= 0;
	attmode			= 1;
	attreq			= 1;
	aunits			= 0;
	auprec			= 0;
	axismode		= 0;
	axisunit[0]		= 0;
	axisunit[1]		= 0;
	backz			= 0;
	blipmode		= 0;
	cecolor			= 255;
	celtscale		= 1;
	celtype			= NULL;
	chamfera		= 0;
	chamferb		= 0;
	chamferc		= 0;
	chamferd		= 0;
	chammode		= 0;
	circlerad		= 0;
	clayer			= NULL;
	cmdactive		= 0;
	cmdecho			= 1;
	cmdnames=NULL;
	db_astrncpy(&cmdnames,"",-1);
	cmljust			= 0;
	cmlscale		= 1;
	cmlstyle		= NULL;
	coords			= 1;
	cvport			= 2;
	cyclecurr		= 5;
	cyclekeep		= 1;
	dbmod			= 0;
	delobj			= 1;
	diastat			= 1;
	dimalt			= 0;
	dimaltd			= 2;
	dimaltf			= 25.4;
	dimalttd		= 2;
	dimalttz		= 0;
	dimaltu			= 2;
	dimaltz			= 0;
	dimapost=NULL;
	db_astrncpy(&dimapost,"",-1);
	dimaso			= 1;
	dimasz			= 0.18;
	dimaunit		= 0;
	dimblk=NULL;
	db_astrncpy(&dimblk,"",-1);
	dimblk1=NULL;
	db_astrncpy(&dimblk1,"",-1);
	dimblk2=NULL;
	db_astrncpy(&dimblk2,"",-1);
	// EBATECH(watanabe)-[dimldrblk
	dimldrblk=NULL;
	db_astrncpy(&dimldrblk,"",-1);
	// ]-EBATECH(watanabe)
	dimcen			= 0.09;
	dimclrd			= 0;
	dimclre			= 0;
	dimclrt			= 0;
	dimdec			= 4;
	dimadec			= -1; // EBATECH(CNBR)  Bugzilla#78443 2003/2/7
	dimdle			= 0;
	dimdli			= 0.38;
	dimexe			= 0.18;
	dimexo			= 0.0625;
	dimfit			= 3;
	dimgap			= 0.09;
	dimjust			= 0;
	dimlfac			= 1;
	dimlim			= 0;
	dimpost=NULL;
	db_astrncpy(&dimpost,"",-1);
	dimrnd			= 0;
	dimsah			= 0;
	dimscale		= 1;
	dimsd1			= 0;
	dimsd2			= 0;
	dimse1			= 0;
	dimse2			= 0;
	dimsho			= 1;
	dimsoxd			= 0;
	dimstyle		= NULL;
	dimtad			= 0;
	dimtdec			= 4;
	dimtfac			= 1;
	dimtih			= 1;
	dimtix			= 0;
	dimtm			= 0;
	dimtofl			= 0;
	dimtoh			= 1;
	dimtol			= 0;
	dimtolj			= 1;
	dimtp			= 0;
	dimtsz			= 0;
	dimtvp			= 0;
	dimtxsty		= NULL;
	dimtxt			= 0.18;
	dimtzin			= 0;
	dimunit			= 2;
	dimupt			= 0;
	dimzin			= 0;
	dimazin			= 0; // EBATECH(CNBR)  Bugzilla#78443 2003/2/7
	dispsilh		= 0;
	distance		= 0;
	donutid			= 0.5;
	donutod			= 1;
	dragmode		= 2;
// EBATECH(CNBR) -[ Set Default DWGCODEPAGE from ActiveCodepage
//	dwgcodepage		= 30; EBATECH(CNBR)
	{
		char samp[32];
		sprintf(samp, "ANSI_%d", GetACP());
		if(!adAsciiCodePageToShort(samp,&dwgcodepage))
			dwgcodepage = 30;
	}
// EBATECH(CNBR) ]-
	dwgtitled		= 1;
	edgemode		= 0;
	elevation		= 0;
	explmode		= 1;
	extmax[0]		= 12.0;
	extmax[1]		= 92.0;
	extmax[2]		= 0.0;
	extmin[0]		= 0.0;
	extmin[1]		= 0.0;
	extmin[2]		= 0.0;
	facetres		= 0.5;
	fastzoom		= 1;
	filletrad		= 0;
	fillmode		= 1;
	fittype			= 2;
	flatland		= 0;
	frontz			= 0;
	gpslastpt[0]	= 0.0;
	gpslastpt[1]	= 0.0;
	gpslastpt[2]	= 0.0;
	gpsmode			= 0;
	gpspaused		= 1;
	gpsplayed=NULL;
	db_astrncpy(&gpsplayed,"",-1);
	gridmode		= 0;
	gridunit[0]		= 0.5;
	gridunit[1]		= 0.5;
	handles			= 1;
	highlight		= 1;
	hpang			= 0;
	hpbound			= 1;
	hpdouble		= 0;
	hpname=NULL;
	db_astrncpy(&hpname,"",-1);
	hpscale			= 1;
	hpspace			= 1;
	hpstyle			= 0;
	insbase[0]		= 0;
	insbase[1]		= 0;
	insbase[2]		= 0;
	insname=NULL;
	db_astrncpy(&insname,"",-1);
	islastcmdpt		= 0;
	isolines		= 4;
	lastangle		= 0;
	lastcmdang		= 0.0;
	lastcmdpt[0]	= 0.0;
	lastcmdpt[1]	= 0.0;
	lastcmdpt[2]	= 0.0;
	lastpoint[0]	= 0;
	lastpoint[1]	= 0;
	lastpoint[2]	= 0;
	lenslength		= 50;
	limcheck		= 0;
	limmax[0]		= 12;
	limmax[1]		= 9;
	limmin[0]		= 0;
	limmin[1]		= 0;
	ltscale			= 1;
	ltsclwblk		= 0;
	lunits			= 2;
	luprec			= 4;
	maxactvp		= 64; // Old value is 16
	measurement		= 0;
	menuecho		= 0;
	menuname=NULL;
	db_astrncpy(&menuname,"icad",-1);
	mirrtext		= 1;
	offsetdist		= -1;
	orthomode		= 0;
	osmode			= 0;
	pdmode			= 0;
	pdsize			= 0;
	pellipse		= 0;
	perimeter		= 0;
	pickstyle		= 1;
	plinegen		= 0;
	plinewid		= 0;
	polysides		= 4;
	proxygraphics	= 1;
	psltscale		= 1;
	p_elevation		= 0;
	p_extmax[0]		= -1E+20;
	p_extmax[1]		= -1E+20;
	p_extmax[2]		= -1E+20;
	p_extmin[0]		= 1E+20;
	p_extmin[1]		= 1E+20;
	p_extmin[2]		= 1E+20;
	p_insbase[0]	= 0;
	p_insbase[1]	= 0;
	p_insbase[2]	= 0;
	p_limcheck		= 0;
	p_limmax[0]		= 12;
	p_limmax[1]		= 9;
	p_limmin[0]		= 0;
	p_limmin[1]		= 0;
	p_ucsname		= NULL;
	p_ucsorg[0]		= 0;
	p_ucsorg[1]		= 0;
	p_ucsorg[2]		= 0;
	p_ucsxdir[0]	= 1;
	p_ucsxdir[1]	= 0;
	p_ucsxdir[2]	= 0;
	p_ucsydir[0]	= 0;
	p_ucsydir[1]	= 1;
	p_ucsydir[2]	= 0;
	qtextmode		= 0;
	regenmode		= 1;
	saveimages		= 0;
	savename=NULL;
	db_astrncpy(&savename,"",-1);
	shadedge		= 3;
	shadedif		= 70;
	shpname=NULL;
	db_astrncpy(&shpname,"",-1);
	sketchinc		= 0.1;
	skpoly			= 0;
	snapang			= 0;
	snapbase[0]		= 0;
	snapbase[1]		= 0;
	snapisopair		= 0;
	snapmode		= 0;
	snapstyl		= 0;
	snapunit[0]		= 0.5;
	snapunit[1]		= 0.5;
	splframe		= 0;
	splinesegs		= 8;
	splinetype		= 5;
	surftab1		= 6;
	surftab2		= 6;
	surftype		= 6;
	surfu			= 6;
	surfv			= 6;
	target[0]		= 0;
	target[1]		= 0;
	target[2]		= 0;
	tdcreate		= 2444240;
	tdindwg			= 0;
	tdupdate		= 2444240;
	tdusrtimer		= 0;
	textangle		= 0.0;
	textqlty		= 50;
	textsize		= 0.2;
	textstyle		= NULL;
	thickness		= 0;
	tilemode		= 1;
	tracewid		= 0.05;
	treedepth		= 3020;
	trimmode		= 1;
	ucsfollow		= 0;
	ucsicon			= 1;
	ucsname			= NULL;
	ucsorg[0]		= 0;
	ucsorg[1]		= 0;
	ucsorg[2]		= 0;
	ucsxdir[0]		= 1;
	ucsxdir[1]		= 0;
	ucsxdir[2]		= 0;
	ucsydir[0]		= 0;
	ucsydir[1]		= 1;
	ucsydir[2]		= 0;
	undoctl			= 5;
	undomarks		= 0;
	unitmode		= 0;
	useri1			= 0;
	useri2			= 0;
	useri3			= 0;
	useri4			= 0;
	useri5			= 0;
	userr1			= 0;
	userr2			= 0;
	userr3			= 0;
	userr4			= 0;
	userr5			= 0;
	users1=NULL;
	db_astrncpy(&users1,"",-1);
	users2=NULL;
	db_astrncpy(&users2,"",-1);
	users3=NULL;
	db_astrncpy(&users3,"",-1);
	users4=NULL;
	db_astrncpy(&users4,"",-1);
	users5=NULL;
	db_astrncpy(&users5,"",-1);
	usrtimer		= 1;
	viewaspect		= 1.0;
	viewctr[0]		= 6.24334;
	viewctr[1]		= 4.24334;
	viewctr[2]		= 0;
	viewdir[0]		= 0;
	viewdir[1]		= 0;
	viewdir[2]		= 1;
	viewmode		= 0;
	viewsize		= 9;
	viewtwist		= 0;
	visretain		= 0;
	vsmax[0]		= 10;
	vsmax[1]		= 10;
	vsmax[2]		= 0;
	vsmin[0]		= 0;
	vsmin[1]		= 0;
	vsmin[2]		= 0;
	worlducs		= 1;
	worldview		= 1;
	writestat		= 1;
	zoompercent		= 100;
	};

db_header::~db_header(void)
	{
	if (cmdnames		!= NULL)	delete cmdnames;
	if (dimapost		!= NULL)	delete dimapost;
	if (dimblk			!= NULL)	delete dimblk;
	if (dimblk1			!= NULL)	delete dimblk1;
	if (dimblk2			!= NULL)	delete dimblk2;
	// EBATECH(watanabe)-[dimldrblk
	if (dimldrblk		!= NULL)	delete dimldrblk;
	// ]-EBATECH(watanabe)
	if (dimpost			!= NULL)	delete dimpost;
	if (gpsplayed		!= NULL)	delete gpsplayed;
	if (hpname			!= NULL)	delete hpname;
	if (insname			!= NULL)	delete insname;
	if (menuname		!= NULL)	delete menuname;
	if (savename		!= NULL)	delete savename;
	if (shpname			!= NULL)	delete shpname;
	if (users1			!= NULL)	delete users1;
	if (users2			!= NULL)	delete users2;
	if (users3			!= NULL)	delete users3;
	if (users4			!= NULL)	delete users4;
	if (users5			!= NULL)	delete users5;
	};

