// DWG sysvar search structs -- automatically generated -- do not edit
// Copyright (c) 1999, Visio Corporation.  All rights reserved.

#ifndef _INC_SYSVAR_SEARCH_H
#define _INC_SYSVAR_SEARCH_H

struct sysvarshortsearchstru sysvarshortsearchdata[]=
	{
	{ "APERTURE",			&db_sysvar::SetAperture,		&db_sysvar::RetAperture 		,true,  true,  false,   0,  50,  true }, 
	{ "AUDITCTL",			&db_sysvar::SetAuditctl,		&db_sysvar::RetAuditctl 		,true,  true,  false,   0,   1,  true }, 
	{ "AUTOMENULOAD",		&db_sysvar::SetAutomenuload,	&db_sysvar::RetAutomenuload 	,true,  true,  false,   0,   1,  true }, 
	{ "BKGCOLOR",			&db_sysvar::SetBkgcolor,		&db_sysvar::RetBkgcolor 		,true,  true,  false,   0, 256,  true }, 
	{ "BKGREDRAW",			&db_sysvar::SetBkgredraw,		&db_sysvar::RetBkgredraw 		,true,  true,  false,   0,   1,  true }, 
	{ "CMDDIA",				&db_sysvar::SetCmddia,			&db_sysvar::RetCmddia 			,true,  true,  false,   0,   1,  true }, 
	{ "COLORX",				&db_sysvar::SetColorx,			&db_sysvar::RetColorx 			,true,  true,  false,   0, 256,  true }, 
	{ "COLORY",				&db_sysvar::SetColory,			&db_sysvar::RetColory 			,true,  true,  false,   0, 256,  true }, 
	{ "COLORZ",				&db_sysvar::SetColorz,			&db_sysvar::RetColorz 			,true,  true,  false,   0, 256,  true }, 
	{ "DIMSS",				&db_sysvar::SetDimSS,			&db_sysvar::RetDimSS			,true,	true,  false,	0,	 1,	 true },
	{ "DIMSSPOS",			&db_sysvar::SetDimSSPos,		&db_sysvar::RetDimSSPos			,true,	true,  false,	0,	 5,	 true },
	{ "DRAGOPEN",			&db_sysvar::SetDragopen,		&db_sysvar::RetDragopen 		,true,  true,  false,   0,   1,  true }, 
	{ "DRAGP1",				&db_sysvar::SetDragp1,			&db_sysvar::RetDragp1 			,true,  true,  false,   0, 32767,  true }, 
	{ "DRAGP2",				&db_sysvar::SetDragp2,			&db_sysvar::RetDragp2 			,true,  true,  false,   0, 32767,  true }, 
	{ "ERRNO",				&db_sysvar::SetErrorno,			&db_sysvar::RetErrorno 			,false, false, false,  0,   0,  false }, 
	{ "EXPERT",				&db_sysvar::SetExpert,			&db_sysvar::RetExpert 			,true,  true,  false,   0,   5,  false }, 
	{ "EXPLEVEL",			&db_sysvar::SetExplevel,		&db_sysvar::RetExplevel 		,true,  true,  false,   1,   3,  true }, 
	{ "FFLIMIT",			&db_sysvar::SetFflimit,			&db_sysvar::RetFflimit 			,true,  true,  false,   0, 100,  true }, 
	{ "FILEDIA",			&db_sysvar::SetFiledia,			&db_sysvar::RetFiledia 			,true,  true,  false,   0,   1,  true }, 
	{ "GLOBCHECK",			&db_sysvar::SetGlobcheck,		&db_sysvar::RetGlobcheck 		,true,  true,  false,   0,   3,  false }, 
	{ "GRIPBLOCK",			&db_sysvar::SetGripblock,		&db_sysvar::RetGripblock 		,true,  true,  false,   0,   1,  true }, 
	{ "GRIPCOLOR",			&db_sysvar::SetGripcolor,		&db_sysvar::RetGripcolor 		,true,  true,  false,   1, 255,  true }, 
	{ "GRIPHOT",			&db_sysvar::SetGriphot,			&db_sysvar::RetGriphot 			,true,  true,  false,   1, 255,  true }, 
	{ "GRIPS",				&db_sysvar::SetGrips,			&db_sysvar::RetGrips 			,true,  true,  false,   0,   1,  true }, 
	{ "GRIPSIZE",			&db_sysvar::SetGripsize,		&db_sysvar::RetGripsize 		,true,  true,  false,   1, 255,  true }, 
	{ "HANDUDCOPY",			&db_sysvar::SetHandudcopy,		&db_sysvar::RetHandudcopy 		,true,  true,  false,   0,   1,  false }, 
	{ "ISAVEPERCENT",		&db_sysvar::SetIsavepercent,	&db_sysvar::RetIsavepercent 	,true,  true,  false,   0, 100,  true }, 
	{ "LOGFILEMODE",		&db_sysvar::SetLogfilemode,		&db_sysvar::RetLogfilemode 		,true,  true,  false,   0,   1,  false }, 
	{ "LONGFNAME",			&db_sysvar::SetLongfname,		&db_sysvar::RetLongfname 		,true,  true,  false,   0,   1,  true }, 
	{ "LWPOLYOUT",			&db_sysvar::SetLwpolyout,		&db_sysvar::RetLwpolyout 		,true,  true,  false,   0,   1,  true }, 
	{ "MACROREC",			&db_sysvar::SetMacrorec,		&db_sysvar::RetMacrorec 		,true,  true,  false,   0,   1,  false }, 
	{ "MACROTRACE",			&db_sysvar::SetMacrotrace,		&db_sysvar::RetMacrotrace 		,true,  true,  false,   0,   1,  false }, 
	{ "MAKEBAK",			&db_sysvar::SetMakebak,			&db_sysvar::RetMakebak 			,true,  true,  false,   0,   1,  true }, 
	{ "MAXSORT",			&db_sysvar::SetMaxsort,			&db_sysvar::RetMaxsort 			,true,  true,  false,   0, 32767,  true }, 
	{ "MBUTTONPAN",			&db_sysvar::SetMbuttonpan,		&db_sysvar::RetMbuttonpan		,true,	true,  false,	0,	 1,	 true },
	{ "MENUCTL",			&db_sysvar::SetMenuctl,			&db_sysvar::RetMenuctl 			,true,  true,  false,   0,   1,  true }, 
	{ "NFILELIST",			&db_sysvar::SetNfilelist,		&db_sysvar::RetNfilelist 		,true,  true,  false,   0,  10,  true }, 
	{ "PFACEVMAX",			&db_sysvar::SetPfacevmax,		&db_sysvar::RetPfacevmax 		,true,  false, false,   3,   0,  false }, 
	{ "PICKADD",			&db_sysvar::SetPickadd,			&db_sysvar::RetPickadd 			,true,  true,  false,   0,   1,  true }, 
	{ "PICKAUTO",			&db_sysvar::SetPickauto,		&db_sysvar::RetPickauto 		,true,  true,  false,   0,   1,  true }, 
	{ "PICKBOX",			&db_sysvar::SetPickbox,			&db_sysvar::RetPickbox 			,true,  true,  false,   0, 32767,  true }, 
	{ "PICKDRAG",			&db_sysvar::SetPickdrag,		&db_sysvar::RetPickdrag 		,true,  true,  false,   0,   1,  true }, 
	{ "PICKFIRST",			&db_sysvar::SetPickfirst,		&db_sysvar::RetPickfirst 		,true,  true,  false,   0,   1,  true }, 
	{ "PLINETYPE",			&db_sysvar::SetPlinetype,		&db_sysvar::RetPlinetype 		,true,  true,  false,   0,   2,  true }, 
	{ "PLOTROTMODE",		&db_sysvar::SetPlotrotmode,		&db_sysvar::RetPlotrotmode 		,true,  true,  false,   0,   1,  true }, 
	{ "PLOTTER",			&db_sysvar::SetPlotter,			&db_sysvar::RetPlotter 			,true,  true,  false,   0,   0,  true }, 
	{ "POPUPS",				&db_sysvar::SetPopups,			&db_sysvar::RetPopups 			,true,  true,  true,   0,   1,  false }, 
	{ "PROGBAR",			&db_sysvar::SetProgbar,			&db_sysvar::RetProgbar 			,true,  true,  false,   0,   1,  false }, 
	{ "PROJMODE",			&db_sysvar::SetProjmode,		&db_sysvar::RetProjmode 		,true,  true,  false,   0,   2,  true }, 
	{ "PROMPTMENU",			&db_sysvar::SetPromptmenu,		&db_sysvar::RetPromptmenu 		,true,  true,  false,   0,   1,  true }, 
	{ "PSQUALITY",			&db_sysvar::SetPsquality,		&db_sysvar::RetPsquality 		,true,  true,  false, -32768, 32767,  true }, 
	{ "QAFLAGS",			&db_sysvar::SetQaflags,			&db_sysvar::RetQaflags 			,true,  true,  false,   0, 32767,  true }, 
	{ "RASTERPREVIEW",		&db_sysvar::SetRasterpreview,	&db_sysvar::RetRasterpreview 	,true,  true,  false,   0,   1,  true }, 
	{ "RE_INIT",			&db_sysvar::SetRe_init,			&db_sysvar::RetRe_init 			,false, false, false,  0,   0,  false }, 
	{ "SAVETIME",			&db_sysvar::SetSavetime,		&db_sysvar::RetSavetime 		,true,  true,  false,   0, 32767,  true }, 
	{ "SCREENBOXES",		&db_sysvar::SetScreenboxes,		&db_sysvar::RetScreenboxes 		,true,  false, false,   0,   0,  true }, 
	{ "SCREENMODE",			&db_sysvar::SetScreenmode,		&db_sysvar::RetScreenmode 		,true,  true,  true,   0,   2,  true }, 
	{ "SCRLHIST",			&db_sysvar::SetScrlhist,		&db_sysvar::RetScrlhist 		,true,  false, false,   0,   0,  true }, 
	{ "SORTENTS",			&db_sysvar::SetSortents,		&db_sysvar::RetSortents 		,true,  true,  false,   1, 127,  true }, 
	{ "TABMODE",			&db_sysvar::SetTabmode,			&db_sysvar::RetTabmode 			,true,  true,  false,   0,   1,  false }, 
	{ "TBCOLOR",			&db_sysvar::SetTbcolor,			&db_sysvar::RetTbcolor 			,true,  true,  false,   0,   1,  true }, 
	{ "TBSIZE",				&db_sysvar::SetTbsize,			&db_sysvar::RetTbsize 			,true,  true,  false,   0,   1,  true }, 
	{ "TEXTEVAL",			&db_sysvar::SetTexteval,		&db_sysvar::RetTexteval 		,true,  true,  false,   0,   1,  false }, 
	{ "TEXTFILL",			&db_sysvar::SetTextfill,		&db_sysvar::RetTextfill 		,true,  true,  false,   0,   1,  true }, 
	{ "TIPOFDAY",			&db_sysvar::SetTipofday,		&db_sysvar::RetTipofday 		,true,  true,  false,   0,   1,  true }, 
	{ "TOOLTIPS",			&db_sysvar::SetTooltips,		&db_sysvar::RetTooltips 		,true,  true,  false,   0,   1,  true }, 
	{ "UCSICONPOS",			&db_sysvar::SetUcsiconpos,		&db_sysvar::RetUcsiconpos 		,true,  true,  false,   0,   3,  true }, 
	{ "WNDBTEXP",			&db_sysvar::SetWndbtexp,		&db_sysvar::RetWndbtexp 		,false, false, false,  0,   0,  true }, 
	{ "WNDLCMD",			&db_sysvar::SetWndlcmd,			&db_sysvar::RetWndlcmd 			,true,  true,  false,   0,   3,  true }, 
	{ "WNDLMAIN",			&db_sysvar::SetWndlmain,		&db_sysvar::RetWndlmain 		,true,  true,  false,   0,   2,  true }, 
	{ "WNDLMDI",			&db_sysvar::SetWndlmdi,			&db_sysvar::RetWndlmdi 			,true,  true,  true,   0,   2,  true }, 
	{ "WNDLSCRL",			&db_sysvar::SetWndlscrl,		&db_sysvar::RetWndlscrl 		,true,  true,  false,   0,   1,  true }, 
	{ "WNDLSTAT",			&db_sysvar::SetWndlstat,		&db_sysvar::RetWndlstat 		,true,  true,  false,   0,   1,  true }, 
	{ "WNDLTEXP",			&db_sysvar::SetWndltexp,		&db_sysvar::RetWndltexp 		,true,  true,  false,   0,   2,  true }, 
	{ "WNDLTEXT",			&db_sysvar::SetWndltext,		&db_sysvar::RetWndltext 		,true,  true,  false,   0,   3,  true }, 
	{ "XLOADCTL",			&db_sysvar::SetXloadctl,		&db_sysvar::RetXloadctl 		,true,  true,  false,   0,   2,  true }, 
	{ "XREFCTL",			&db_sysvar::SetXrefctl,			&db_sysvar::RetXrefctl 			,true,  true,  false,   0,   1,  true }, 
	{ "ZOOMFACTOR",			&db_sysvar::SetZoomfactor,		&db_sysvar::RetZoomfactor		,true,	true,  false,	3, 100,  true },
	};

struct sysvarstringsearchstru sysvarstringsearchdata[]=
	{
	{ "BASEFILE",			&db_sysvar::SetBasefile,		&db_sysvar::RetBasefile 		,  true }, 
	{ "CMDLNTEXT",			&db_sysvar::SetCmdlntext,		&db_sysvar::RetCmdlntext 		,  true }, 
	{ "DCTCUST",			&db_sysvar::SetDctcust,			&db_sysvar::RetDctcust 			,  true }, 
	{ "DCTMAIN",			&db_sysvar::SetDctmain,			&db_sysvar::RetDctmain 			,  true }, 
	{ "EXPLSTBLK",			&db_sysvar::SetExplstblk,		&db_sysvar::RetExplstblk 		,  true }, 
	{ "EXPLSTDS",			&db_sysvar::SetExplstds,		&db_sysvar::RetExplstds 		,  true }, 
	{ "EXPLSTLAY",			&db_sysvar::SetExplstlay,		&db_sysvar::RetExplstlay 		,  true }, 
	{ "EXPLSTLT",			&db_sysvar::SetExplstlt,		&db_sysvar::RetExplstlt 		,  true }, 
	{ "EXPLSTTS",			&db_sysvar::SetExplstts,		&db_sysvar::RetExplstts 		,  true }, 
	{ "EXPLSTUCS",			&db_sysvar::SetExplstucs,		&db_sysvar::RetExplstucs 		,  true }, 
	{ "EXPLSTVW",			&db_sysvar::SetExplstvw,		&db_sysvar::RetExplstvw 		,  true }, 
	{ "FONTALT",			&db_sysvar::SetFontalt,			&db_sysvar::RetFontalt 			,  true }, 
	{ "FONTMAP",			&db_sysvar::SetFontmap,			&db_sysvar::RetFontmap 			,  true }, 
	{ "LASTPROMPT",			&db_sysvar::SetLastprompt,		&db_sysvar::RetLastprompt 		,  false }, 
	{ "LOGFILENAME",		&db_sysvar::SetLogfilename,		&db_sysvar::RetLogfilename 		,  false }, 
	{ "LOGINNAME",			&db_sysvar::SetLoginname,		&db_sysvar::RetLoginname 		,  true }, 
	{ "MODEMACRO",			&db_sysvar::SetModemacro,		&db_sysvar::RetModemacro 		,  false }, 
	{ "MTEXTED",			&db_sysvar::SetMtexted,			&db_sysvar::RetMtexted 			,  true }, 
	{ "PLOTID",				&db_sysvar::SetPlotid,			&db_sysvar::RetPlotid 			,  true }, 
	{ "PSPROLOG",			&db_sysvar::SetPsprolog,		&db_sysvar::RetPsprolog 		,  true }, 
	{ "SAVEFILE",			&db_sysvar::SetSavefile,		&db_sysvar::RetSavefile 		,  true }, 
	{ "SRCHPATH",			&db_sysvar::SetSrchpath,		&db_sysvar::RetSrchpath 		,  true }, 
	{ "TEMPPREFIX",			&db_sysvar::SetTempprefix,		&db_sysvar::RetTempprefix 		,  true }, 
	{ "XLOADPATH",			&db_sysvar::SetXloadpath,		&db_sysvar::RetXloadpath 		,  true }, 
	{ "_VERNUM",			&db_sysvar::Set_vernum,			&db_sysvar::Ret_vernum 			,  false }, 
	};

struct sysvarpointsearchstru sysvarpointsearchdata[]=
	{
	{ "SCREENPOS",			&db_sysvar::SetScreenpos,		&db_sysvar::GetScreenpos 		,  true }, 
	{ "SCREENSIZE",			&db_sysvar::SetScreensize,		&db_sysvar::GetScreensize 		,  true }, 
	{ "WNDPCMD",			&db_sysvar::SetWndpcmd,			&db_sysvar::GetWndpcmd 			,  true }, 
	{ "WNDPFORM",			&db_sysvar::SetWndpform,		&db_sysvar::GetWndpform 		,  true }, 
	{ "WNDPMAIN",			&db_sysvar::SetWndpmain,		&db_sysvar::GetWndpmain 		,  true }, 
	{ "WNDPPMENU",			&db_sysvar::SetWndppmenu,		&db_sysvar::GetWndppmenu 		,  true }, 
	{ "WNDPTEXP",			&db_sysvar::SetWndptexp,		&db_sysvar::GetWndptexp 		,  true }, 
	{ "WNDPTEXT",			&db_sysvar::SetWndptext,		&db_sysvar::GetWndptext 		,  true }, 
	{ "WNDSCMD",			&db_sysvar::SetWndscmd,			&db_sysvar::GetWndscmd 			,  true }, 
	{ "WNDSFORM",			&db_sysvar::SetWndsform,		&db_sysvar::GetWndsform 		,  true }, 
	{ "WNDSMAIN",			&db_sysvar::SetWndsmain,		&db_sysvar::GetWndsmain 		,  true }, 
	{ "WNDSTEXP",			&db_sysvar::SetWndstexp,		&db_sysvar::GetWndstexp 		,  true }, 
	{ "WNDSTEXT",			&db_sysvar::SetWndstext,		&db_sysvar::GetWndstext 		,  true }, 
	};

#endif
