// DWG sysvar constructor/destructor -- automatically generated -- do not edit
// Copyright (c) 1999, Visio Corporation.  All rights reserved.

#include "db.h"
db_sysvar::db_sysvar(void)
	{
	aperture		= 10;
	auditctl		= 0;
	automenuload	= 1;
	basefile=NULL;
	db_astrncpy(&basefile,"icad.dwt",-1);
	bkgcolor		= 256;
	bkgredraw		= 0;
	cmddia			= 1;
	cmdlntext=NULL;
	db_astrncpy(&cmdlntext,":",-1);
	colorx			= 1;
	colory			= 3;
	colorz			= 5;
	dctcust=NULL;
	db_astrncpy(&dctcust,"",-1);
	dctmain=NULL;
	db_astrncpy(&dctmain,"",-1);
	dimss			= 0;
	dimsspos		= 2;
	dragopen		= 1;
	dragp1			= 10;
	dragp2			= 25;
	errorno			= 0;
	expert			= 0;
	explevel		= 3;
	explstblk=NULL;
	db_astrncpy(&explstblk,"",-1);
	explstds=NULL;
	db_astrncpy(&explstds,"",-1);
	explstlay=NULL;
	db_astrncpy(&explstlay,"",-1);
	explstlt=NULL;
	db_astrncpy(&explstlt,"",-1);
	explstts=NULL;
	db_astrncpy(&explstts,"",-1);
	explstucs=NULL;
	db_astrncpy(&explstucs,"",-1);
	explstvw=NULL;
	db_astrncpy(&explstvw,"",-1);
	fflimit			= 0;
	filedia			= 1;
	fontalt=NULL;
	db_astrncpy(&fontalt,"txt",-1);
	fontmap=NULL;
	db_astrncpy(&fontmap,"icad.fmp",-1);
	globcheck		= 0;
	gripblock		= 0;
	gripcolor		= 3;
	griphot			= 1;
	grips			= 1;
	gripsize		= 3;
	handudcopy		= 0;
	isavepercent	= 50;
	lastprompt=NULL;
	db_astrncpy(&lastprompt,"",-1);
	logfilemode		= 0;
	logfilename=NULL;
	db_astrncpy(&logfilename,"icad.log",-1);
	loginname=NULL;
	db_astrncpy(&loginname,"IntelliCAD User",-1);
	longfname		= 1;
	lwpolyout		= 1;
	macrorec		= 0;
	macrotrace		= 0;
	makebak			= 1;
	maxsort			= 200;
	mbuttonpan		= 1;
	menuctl			= 1;
	modemacro=NULL;
	db_astrncpy(&modemacro,"",-1);
	mtexted=NULL;
	db_astrncpy(&mtexted,"",-1);
	nfilelist		= 4;
	pfacevmax		= 4;
	pickadd			= 1;
	pickauto		= 1;
	pickbox			= 3;
	pickdrag		= 0;
	pickfirst		= 1;
	plinetype		= 2;
	plotid=NULL;
	db_astrncpy(&plotid,"",-1);
	plotrotmode		= 1;
	plotter			= 0;
	popups			= 1;
	progbar			= 1;
	projmode		= 1;
	promptmenu		= 1;
	psprolog=NULL;
	db_astrncpy(&psprolog,"",-1);
	psquality		= 75;
	qaflags			= 0;
	rasterpreview	= 1;
	re_init			= 0;
	savefile=NULL;
	db_astrncpy(&savefile,".SV$",-1);
	savetime		= 60;
	screenboxes		= 26;
	screenmode		= 1;
	screenpos[0]	= 640;
	screenpos[1]	= 480;
	screensize[0]	= 640;
	screensize[1]	= 480;
	scrlhist		= 256;
	sortents		= 96;
	srchpath=NULL;
	db_astrncpy(&srchpath,"",-1);
	tabmode			= 0;
	tbcolor			= 1;
	tbsize			= 0;
	tempprefix=NULL;
	db_astrncpy(&tempprefix,"",-1);
	texteval		= 0;
	textfill		= 1;
	tipofday		= 1;
	tooltips		= 1;
	ucsiconpos		= 0;
	wndbtexp		= 0;
	wndlcmd			= 0;
	wndlmain		= 2;
	wndlmdi			= 2;
	wndlscrl		= 0;
	wndlstat		= 1;
	wndltexp		= 1;
	wndltext		= 0;
	wndpcmd[0]		= 0;
	wndpcmd[1]		= 0;
	wndpform[0]		= 0;
	wndpform[1]		= 0;
	wndpmain[0]		= 0;
	wndpmain[1]		= 0;
	wndppmenu[0]	= 0;
	wndppmenu[1]	= 0;
	wndptexp[0]		= 0;
	wndptexp[1]		= 0;
	wndptext[0]		= 0;
	wndptext[1]		= 0;
	wndscmd[0]		= 0;
	wndscmd[1]		= 0;
	wndsform[0]		= 0;
	wndsform[1]		= 0;
	wndsmain[0]		= 0;
	wndsmain[1]		= 0;
	wndstexp[0]		= 0;
	wndstexp[1]		= 0;
	wndstext[0]		= 0;
	wndstext[1]		= 0;
	xloadctl		= 1;
	xloadpath=NULL;
	db_astrncpy(&xloadpath,"",-1);
	xrefctl			= 0;
	zoomfactor		= 10;
	_vernum=NULL;
	db_astrncpy(&_vernum,"?",-1);
	IcadSharedGlobals::SetSysvarPtr(this);
	};

db_sysvar::~db_sysvar(void)
	{
	if (basefile		!= NULL)	delete basefile;
	if (cmdlntext		!= NULL)	delete cmdlntext;
	if (dctcust			!= NULL)	delete dctcust;
	if (dctmain			!= NULL)	delete dctmain;
	if (explstblk		!= NULL)	delete explstblk;
	if (explstds		!= NULL)	delete explstds;
	if (explstlay		!= NULL)	delete explstlay;
	if (explstlt		!= NULL)	delete explstlt;
	if (explstts		!= NULL)	delete explstts;
	if (explstucs		!= NULL)	delete explstucs;
	if (explstvw		!= NULL)	delete explstvw;
	if (fontalt			!= NULL)	delete fontalt;
	if (fontmap			!= NULL)	delete fontmap;
	if (lastprompt		!= NULL)	delete lastprompt;
	if (logfilename		!= NULL)	delete logfilename;
	if (loginname		!= NULL)	delete loginname;
	if (modemacro		!= NULL)	delete modemacro;
	if (mtexted			!= NULL)	delete mtexted;
	if (plotid			!= NULL)	delete plotid;
	if (psprolog		!= NULL)	delete psprolog;
	if (savefile		!= NULL)	delete savefile;
	if (srchpath		!= NULL)	delete srchpath;
	if (tempprefix		!= NULL)	delete tempprefix;
	if (xloadpath		!= NULL)	delete xloadpath;
	if (_vernum			!= NULL)	delete _vernum;
	};

