#ifndef __pc2dispobjH__
#define __pc2dispobjH__

struct gr_view;
/*
**  Needed for llist .pc in struct gr_view below:
*/
struct gr_pclink {
    sds_point			pt;		/* Point in NCS or UCS */
    sds_real			d2go;	/* Distance to go before the ltype pattern */
								/*   generation starts over.  (>=0.0 at pts */
								/*   where gen begins; <0.0 otherwise */
								/*   (using -1.0)).
								/*   Should always be set at least for */
								/*   the 1st pt (viewp->pc itself) -- */
								/*   except when circumventing gr_doltype() */
								/*   by calling gr_gensolid() for entities */
								/*   that are always continuous. */
    sds_real			swid;	/* Starting width (in the NCS) */
    sds_real			ewid;	/* Ending   width (in the NCS) */
	sds_real			startang;	// for polylines and such, the angle to be used if this is the start of a sequence
    sds_real			endang;		// likewise, if this point is the end of a sequence.  The defined constant IC_ANGLE_DONTCARE
									// means there is no angle to be applied
	struct gr_pclink *next;
};

/*
**  The following is for gr_getwidepc() and gr_gensolid().
**  An array of these is generated by gr_getwidepc() using
**  viewp->pc as a template.  Each array element describes the four
**  corners of the corresponding viewp->pc segment once width
**  has been applied.
*/
struct gr_wideseglink {
    sds_point sl;  /* Starting Left  */
    sds_point sr;  /* Starting Right */
    sds_point el;  /* Ending   Left  */
    sds_point er;  /* Ending   Right */
};

short gr_gensolid(
	db_entity				*pSourceEntity,
    struct gr_pclink        *begpclp,
    struct gr_pclink        *endpclp,
    struct gr_pclink        *ilink,
    long                      nintern,
    short                     closed,
    short                     capped,
    sds_point                 dotdir,
    struct gr_displayobject **begpp,
    struct gr_displayobject **endpp,
    struct gr_view           *viewp);
short gr_getwidepc(
    struct gr_pclink        *begpclp,
    struct gr_pclink        *endpclp,
    struct gr_pclink        *ilink,
    long                     nintern,
    short                    closed,
    sds_point                dotdir,
    struct gr_wideseglink  **wsapp,
    struct gr_view          *viewp);

#endif
