/* F:\BLD\PRJ\ICAD\ICADAPI.H
 * Copyright (C) 1997-1998 Visio Corporation. All rights reserved.
 *
 * Abstract
 *
 *
 */

#pragma once


#include "sds.h"/*DNT*/
#include <afxwin.h>
#include <afxtempl.h>

#ifndef _SDS_ENGINE_H
	#include "sds_engine.h"
#endif

//forward declarations
class InputEvent;


#if defined(__cplusplus)
	extern "C"
	{
#endif


//** Defines
#define SDS_EVM_MOUSEXYZ		0x0001	// mouse coordinate in WC
#define SDS_EVM_KEYCHAR			0x0002	// keys and characters
#define SDS_EVM_MOUSEBUTTON		0x0004	// mouse button click
#define SDS_EVM_MENUCOMMAND		0x0008	// menu command
#define SDS_EVM_POPUPCOMMAND	0x0010	// popup menu command string
#define SDS_EVM_AUXMENU  		0x0020	// Aux (right) button click

// AG I added this type of event to enable processing of SDS_AutoLoad generated event
// in the first place
#define SDS_EVM_AUTOEVENT		0x0040	// Event generated by initialization or some other
										// action which should processed in the first place



#define ICAD_WNDACTION_GRAPHSCR 	 4000
#define ICAD_WNDACTION_TEXTSCR		 4001
#define ICAD_WNDACTION_TEXTPAGE		 4002
#define ICAD_WNDACTION_CONFIG		 4003
#define ICAD_WNDACTION_TBLMGR		 4004
#define ICAD_WNDACTION_PRINT		 4005
#define ICAD_WNDACTION_PSETUP		 4006
#define ICAD_WNDACTION_WHTILE		 4007
#define ICAD_WNDACTION_WCASCADE		 4008
#define ICAD_WNDACTION_WOPEN		 4009
#define ICAD_WNDACTION_WCLOSE		 4010
#define ICAD_WNDACTION_EXIT			 4011
#define ICAD_WNDACTION_OSNAP		 4012
#define ICAD_WNDACTION_DIMVARS		 4013
#define ICAD_WNDACTION_INSERT		 4014
#define ICAD_WNDACTION_ATTE 		 4015
#define ICAD_WNDACTION_ATTDEF		 4016
#define ICAD_WNDACTION_SETVAR		 4017
#define ICAD_WNDACTION_UDCOORDS		 4018
#define ICAD_WNDACTION_GPS_PROP 	 4019
#define ICAD_WNDACTION_PPREVIEW		 4020
#define ICAD_WNDACTION_UDSTLAY		 4021
#define ICAD_WNDACTION_UDSTLTP		 4022
#define ICAD_WNDACTION_UDSTCOL		 4023
#define ICAD_WNDACTION_TBCONFIG		 4024
#define ICAD_WNDACTION_UDSBARS		 4025
#define ICAD_WNDACTION_WSPLIT		 4026
#define ICAD_WNDACTION_TIPOFDAY 	 4027
#define ICAD_WNDACTION_WCLOSEALL	 4028
#define ICAD_WNDACTION_WINDOWS		 4029
#define ICAD_WNDACTION_RCLICK		 4030
#define ICAD_WNDACTION_UDSTATBAR	 4031
#define ICAD_WNDACTION_UDCMDBAR 	 4032
#define ICAD_WNDACTION_UDTBARS 		 4033
#define ICAD_WNDACTION_UDGRASCR 	 4034
#define ICAD_WNDACTION_UDTXTSCR 	 4035
#define ICAD_WNDACTION_WVTILE		 4036
#define ICAD_WNDACTION_MODIFY		 4037
#define ICAD_WNDACTION_PROMPTM		 4038
#define ICAD_WNDACTION_NEWMENUS		 4039
#define ICAD_WNDACTION_DELPMTM		 4040
#define ICAD_WNDACTION_FILENEW		 4041
#define ICAD_WNDACTION_UDMDIWND		 4042
#define ICAD_WNDACTION_HIDEPMTM 	 4043
#define ICAD_WNDACTION_SHOWPMTM 	 4044
#define ICAD_WNDACTION_FILEOPEN		 4045
#define ICAD_WNDACTION_FILECLOSE	 4046
#define ICAD_WNDACTION_FILESAVE 	 4047
#define ICAD_WNDACTION_DBMODON		 4048
#define ICAD_WNDACTION_DBMODOFF 	 4049
#define ICAD_WNDACTION_DEFXLINK 	 4050
#define ICAD_WNDACTION_DDNEW		 4051
#define ICAD_WNDACTION_INSOBJ		 4052
#define ICAD_WNDACTION_DDSELECT 	 4053
#define ICAD_WNDACTION_UDOLEOBJ 	 4054
#define ICAD_WNDACTION_COLORDIA 	 (WM_USER+4055)
#define ICAD_WNDACTION_ABOUTDIA 	 4056
#define ICAD_WNDACTION_UDCHKSTAT	 4057
#define ICAD_WNDACTION_CUSTOMIZE	 4058
#define ICAD_WNDACTION_RUNFORM		 4059
#define ICAD_WNDACTION_CURSOROFF	 4060
#define ICAD_WNDACTION_CURSORON 	 4061
#define ICAD_WNDACTION_LASTDRAG 	 4062
#define ICAD_WNDACTION_CHPROP		 4063
#define ICAD_WNDACTION_ATTEXT		 4064
#define ICAD_WNDACTION_UCSP 		 4065
#define ICAD_WNDACTION_VPOINT		 4066
#define ICAD_WNDACTION_UDTBSTATE	 4067
#define ICAD_WNDACTION_UDTBTIPS		 4068
#define ICAD_WNDACTION_TBLUCS		 4069
#define ICAD_WNDACTION_TBLVIEW		 4070
#define ICAD_WNDACTION_TBLSTY		 4071
#define ICAD_WNDACTION_TBLLT		 4072
#define ICAD_WNDACTION_TBLBLK		 4073
#define ICAD_WNDACTION_TBLAPP		 4074
#define ICAD_WNDACTION_EXPASTE		 4075
#define ICAD_WNDACTION_SAVEALL		 4076
#define ICAD_WNDACTION_SHOWTOOLBARS  4077
#define ICAD_WNDACTION_HIDETOOLBARS  4078
#define ICAD_WNDACTION_ISVALIDTBNAME 4079
#define ICAD_WNDACTION_PRINTF		 (WM_USER+4080)
#define ICAD_WNDACTION_XREF 		 4081
#define ICAD_WNDACTION_VIEWCTL		 4082
#define ICAD_WNDACTION_VBA			 4083
#define ICAD_WNDACTION_APPLOAD		 4084
#define ICAD_WNDACTION_SPELL		 4085
#define ICAD_WNDACTION_WIARANGE 	 4086
#define ICAD_WNDACTION_MENUCMD		 4087
#define ICAD_WNDACTION_SETFOCUS 	 4088
#define ICAD_WNDACTION_MDIMIN		 4089
#define ICAD_WNDACTION_MDIMAX		 4090
#define ICAD_WNDACTION_MDIRESTORE	 4091
#define ICAD_WNDACTION_CLOSEVIEW	 4092
#define ICAD_WNDACTION_EDITXDATA	 4093
#define ICAD_WNDACTION_WCLOSEALLBUT  4094
#define ICAD_WNDACTION_MLEDIT		 4095
#define ICAD_WNDACTION_VBALOAD		 4096
#define ICAD_WNDACTION_VBAUNLOAD	 4097
#define ICAD_WNDACTION_VBARUN		 4098
#define ICAD_WNDACTION_MTEXT		 4099
#define ICAD_WNDACTION_TOLERANCE	 4100
#define ICAD_WNDACTION_STATCHANGE	 4101
#define ICAD_WNDACTION_UDSCRLHIST	 4102
#define ICAD_WNDACTION_STARTPROG	 4103
#define ICAD_WNDACTION_UPDATEPROG	 4104
#define ICAD_WNDACTION_ENDPROG		 4105
#define ICAD_WNDACTION_GROUP		 4106
#define ICAD_WNDACTION_PMSPACE		 4107
#define ICAD_WNDACTION_SHOWEXP		 4108
#define ICAD_WNDACTION_QPRINT		 4109
#define ICAD_WNDACTION_RENAMEAPP	 4110
#define ICAD_WNDACTION_COPYHIST 	 4111
#define ICAD_WNDACTION_COPYCLIP		 4112
#define ICAD_WNDACTION_CALCVIEWPTS	 4113
#define ICAD_WNDACTION_LOADMENU		 4114
#define ICAD_WNDACTION_UNLOADMENU	 4115
#define ICAD_WNDACTION_EXP_RETURN	 4116
#define ICAD_WNDACTION_DELOLEITEM	 4117
#define ICAD_WNDACTION_UNSELOLEITEMS 4118
#define ICAD_WNDACTION_PASTESPEC	 4119
#define ICAD_WNDACTION_NEWFONTMAP	 4120
#define ICAD_WNDACTION_RUNFIRSTVIEW	 4121
#define ICAD_WNDACTION_NEWPALETTE	 4122
#define ICAD_WNDACTION_DRAGON  		 4123
#define ICAD_WNDACTION_DRAGOFF		 4124
#define ICAD_WNDACTION_LAYOUTTEMPL	 4125
#define ICAD_WNDACTION_MENUGROUP	 4126
#define ICAD_WNDACTION_OLEUNDOREDO	 4127
#define ICAD_WNDACTION_OLELINKS		 4128
#define ICAD_WNDACTION_INSNAME		 4129
#define ICAD_WNDACTION_XREFDUP		 4130
#define ICAD_WNDACTION_INSDUP		 4131
#define ICAD_WNDACTION_INSCURDWG   	 4132
#define ICAD_WNDACTION_GETDOCLIST	 4133
#define ICAD_WNDACTION_USERCALL 	 4134
#define ICAD_WNDACTION_UPDATE		 4135
#define ICAD_WNDACTION_RND_LIGHT	 4136
#define ICAD_WNDACTION_RND_RENDERPRE 4137
#define ICAD_WNDACTION_RND_RENDERWF  4138
#define ICAD_WNDACTION_RND_RENDERHD  4139
#define ICAD_WNDACTION_RND_RENDERFL  4140
#define ICAD_WNDACTION_RND_EDITMAT	 4141
#define ICAD_WNDACTION_RND_EDITBG	 4142
#define ICAD_WNDACTION_RND_ROPTIONS  4143
#define ICAD_WNDACTION_CHGCVPORT	 4144
#define ICAD_WNDACTION_GETTBPOS		 4145
#define ICAD_WNDACTION_MOVETOOLBAR	 4146
#define ICAD_WNDACTION_ENDDRAG		 4147
#define ICAD_WNDACTION_FREEVIEWRBS	 4148
#define ICAD_WNDACTION_CREATEHBMP	 4149
#define ICAD_WNDACTION_CREATEHWMF	 4150
#define ICAD_WNDACTION_CREATEHEMF	 4151
#define ICAD_WNDACTION_REDRAWALLWIN	 4152
#define ICAD_WNDACTION_ISDOCEMBEDDED 4153
#define ICAD_WNDACTION_SETMRUSIZE	 4154
#define ICAD_WNDACTION_TBLDIMSTY	 4155
#define ICAD_WNDACTION_DOMODAL		 4156
#define ICAD_WNDACTION_BPOLY		 4157
#define ICAD_WNDACTION_BHATCH		 4158
#define ICAD_WNDACTION_UDSCRLBAR	 4159
#define ICAD_WNDACTION_SECURITY 	 4160
#define ICAD_WNDACTION_VBAEXECUTE	 4161
#define ICAD_WNDACTION_TEXT_STYLE	 4162
#define ICAD_WNDACTION_ADDINRUN 	 4163
#define ICAD_WNDACTION_VBAFIRE_REINIT 4164
#define ICAD_WNDACTION_RND_QRENDER	 4165
#define ICAD_WNDACTION_RND_QROPTIONS 4166
#define ICAD_WNDACTION_RESETOSNAPMANAGER 4167
#define ICAD_WNDACTION_PROCESSOSNAPPOINT 4168
#define ICAD_WNDACTION_HYPERLINK	 4169
#define ICAD_WNDACTION_MTEXT2		 4170	// EBATECH(watanabe) -get mtext info only
#define ICAD_WNDACTION_TOLERANCE_EX  4171	// EBATECH(watanabe)
#define ICAD_WNDACTION_UDSTSTY		 4172	// EBATECH(yoji) -Update TextStyle (StatusBar)
#define ICAD_WNDACTION_UDSTDIM		 4173	// EBATECH(yoji) -Update DimStyle (StatusBar)

#define ICAD_WNDACTION_UDSTLW		 4175 //EBATECH update celweight(statusbar)
#define ICAD_WNDACTION_DELEXP		 4176
#define ICAD_WNDACTION_LAYOUT		 4177


#define ICAD_WNDACTION_GETPASSWORD   4200
#define ICAD_WNDACTION_GETDWFINFO    4210

//special dialog messages
#define ICAD_WM_LOAD				 4300
#define ICAD_WM_SAVE				 4301

#define SDS_UNITFILE	 "icad.unt"
#define SDS_DCLFILE 	 "icad.dcl"
#define SDS_RENDERDLL	 "Render.dll"
#define SDS_QRENDERDLL	  "qrender.dll"
#define SDS_ALIASFILE	 "icad.pgp"
#define SDS_PATTERNFILE  "icad.pat"
#define SDS_ISOPATTERNFILE "icadiso.pat"
#define SDS_LTYPEFILE	 "icad.lin"
#define SDS_ISOLTYPEFILE	"icadiso.lin"	// EBATECH(cnbr) Affect $MEASUREMENT
#define SDS_APPNAME 	 "ICAD"
#define SDS_AUTOLOADLISP "icad.lsp"
#define SDS_DBFILE		 "icad.mdb"
#define SDS_LOADSDSFILE  "icad.sds"
#define SDS_APPLOADFILE  "icad.dfs"
#define SDS_PROGRAMFILE  "icad.exe"
#define SDS_TYPELIBFILE  "icad.tlb"
#define SDS_ACISFILE	 "acis.dll"
#define SDS_SHELLFILE	 "$$IntelliCAD_Shell$$.bat"
#define SDS_OURFILEEXT	 ".icd"
#define SDS_SDSFILEEXT	 ".dll"

#define SDS_STARACTIVE	 "*ACTIVE"

#define SDS_TEXTPAGE  0
#define SDS_TEXTSCR	  1
#define SDS_GRAPHSCR  2

#define SDS_USERSPACE	3

//TBLMESSER MODES
#define IC_TBLMESSER_DELETE 0
#define IC_TBLMESSER_MAKE	1
#define IC_TBLMESSER_MODIFY 2
#define IC_TBLMESSER_RENAME 3


// ********************************************
//
// Support for user callbacks from main thread
//
struct UserMainThreadArgs
	{
	int SDS_UserMainThreadFuncRet;
	int (*SDS_UserMainThreadFunc)(void *);
	void *SDS_UserMainThreadFuncData;
	};




//** Special define for demand loading of DLL's.
#define SDS_DEMANDLOAD(DLL,FUNC,PROTO,ARGS,RET) 			   \
{	RET=RTERROR;											   \
	HINSTANCE hInstLib=GetModuleHandle(DLL);				   \
	if(hInstLib==NULL) {									   \
		hInstLib=LoadLibrary(DLL);							   \
	}														   \
	if(hInstLib) {											   \
		int (*LibFunc)PROTO;								   \
		LibFunc=(int (*)PROTO)GetProcAddress(hInstLib,FUNC);   \
		if(LibFunc) {										   \
			RET=(*LibFunc)ARGS;		   						   \
		}													   \
	}														   \
}

// *** Structures
typedef struct //*** Windows metafile information.
	{
	HMETAFILE hMetaFile;
	RECT rectWmf;
	WORD inch;
	} ICADWMFINFO;

struct SDS_ucs_llist {
	sds_point org;
	sds_point xdir;
	sds_point ydir;
	char *name;			//must be freed independently of structure
	struct SDS_ucs_llist *next;
	struct SDS_ucs_llist *prev;
};

struct SDS_textdtext_globalpacket {
	sds_real  lastang;	 //*** Stores the last text angle entered.
	sds_real  txtheight; //*** Stores the last text height entered.
	sds_point nextpt;	 //*** Stores point for next piece of text UNLESS last
						 //		text was aligned or fitted.  Then it keeps text's point
	sds_point nextfitpt; //*** Stores point for next fitted piece of text  UNLESS last
						 //		text was aligned or fitted.  Then it keeps text's point
	sds_name  lastent;	 //*** Stores last ent made, so we can highlight it before making new ent
	char halign;		 //*** Stores last horiz alignment mode
	char valign;		 //*** Stores last vert alignment mode
	char isnextpt;		 //*** Flag indicating a valid next point is available.
};

struct SDS_mTextData {
	sds_point		ptInsertion,				//	Insertion point for block of text
					ptOppCorner;				//	Opposite corner point for block of text
	sds_real		rTextHeight,				//	Text Height		(*** I set the default as 1.0, but I don't know what it is supposed to be.	***)
					rRotAngle  ,				//	Rotation angle for block of text
					rBoxWidth  ;
	char			szTextStyle[IC_ACADBUF];	//	Text Style (default is STANDARD?)
	int				nAlignment,
					nDirection;
	CString			text;

};

struct CNodeData
{
	sds_point m_cen;

	CNodeData(){};
	CNodeData( sds_point cen ){ ic_ptcpy(m_cen, cen); }
};

//4M Item:28->
class MEntNodesArray;

class MNodeData{
private:
	sds_point * points;
   MNodeData * next;
public:
	MNodeData();
	MNodeData(int NoPointsPerBlock);
   MNodeData(MNodeData const &MD);
   MNodeData& operator=(MNodeData const &MD);
   ~MNodeData();
   int Add(int index, sds_point p);
   int Get(int index, sds_point p)const;
   friend class MEntNodesArray;
};

class MEntNodesArray{
private:
   int NoPointsPerBlock;
   int NoPoints;
   int NoBlocks;
   MNodeData * pNodes;
   MNodeData * pLastNode;
public:
   MEntNodesArray();
   MEntNodesArray(int noPointsPerBlock);
   MEntNodesArray(MEntNodesArray const & n);
   MEntNodesArray &operator=(MEntNodesArray const &n);
   ~MEntNodesArray();
   void RemoveAll();
   void SetNoPointsPerBlock(int noPointsPerBlock);
   int GetCount()const{return NoPoints;}
   int Add(sds_point p);
   int Get(int index, sds_point p)const;
};

class CGripNodesArray{
private:
   MEntNodesArray GripNodes;
public:
   CGripNodesArray();
   ~CGripNodesArray();
   void Add(sds_point p);
   void Reset();
   int GetNoGrips()const;
   int GetSize()const{return GripNodes.GetCount();}
   int Get(int index, sds_point p){return GripNodes.Get(index,p);}
};
//<-4M Item:28
//4M Item:25->
// Replacement of SDS_NodeList with SDS_NodeList_new
/*
typedef CArray< CNodeData, CNodeData& > CEntNodesArray;

struct SDS_NodeListDef {
	sds_name ename;
	CEntNodesArray ptArray;
	SDS_NodeListDef *next;

	SDS_NodeListDef(){ ename[0] = ename[1] =0L; next = NULL; }
	SDS_NodeListDef( sds_name name ){ ic_encpy(ename, name); next = NULL; }
};

class SDS_NodeList
{
public:
	SDS_NodeListDef *m_beg, *m_end;

	SDS_NodeList(){ m_beg = m_end = NULL;}
	~SDS_NodeList();
	void add( sds_name ename, sds_point pt );
	void remove( sds_name ename );
	void removeAll();

	// Iterate through all points
	void begin();
	BOOL getPair( sds_name ename, sds_point pt );

protected:
	SDS_NodeListDef *find( sds_name ename, SDS_NodeListDef *&prev, SDS_NodeListDef *&next );

private:
	SDS_NodeListDef *m_cur;
	int m_ptIdx;
};
*/
#include "CSdsName.h"

class NodePoints{
private:
   MEntNodesArray Points;
public:
   NodePoints();
   NodePoints(sds_point pt);
   NodePoints(const NodePoints &n);
   ~NodePoints();
   NodePoints& operator=(const NodePoints &n);
   void Add(sds_point pt);
   int GetSize()const;
   void GetAt(int ind, sds_point pt){Points.Get(ind,pt);}
};


class SDS_NodeList_New
{
private:
	POSITION m_pos;
	CSdsName m_curhandle;
   int m_ptIdx;
   NodePoints  m_CurNodePoints;
   int m_NoPoints;
   CMap<CSdsName, CSdsName&, NodePoints, NodePoints&> EntitiesWithNodes;
public:
   SDS_NodeList_New();
	~SDS_NodeList_New();
	void add( sds_name handle, sds_point pt );
	void remove( sds_name handle );
	void removeAll();
   int GetNoEntities(){return EntitiesWithNodes.GetCount();}

	// Iterate through all points
	void begin();
	BOOL getPair( sds_name ename, sds_point pt );
   BOOL getEntityName( sds_name ename);

private:
   BOOL find( CSdsName handle, NodePoints &);
};
//<-4M Item:25


struct SDS_GrDrawStruct {
	sds_point pt1;
	sds_point pt2;
	int col;
	int hl;
};


struct SDS_CmdHist {
	char   *cmd;
	struct	SDS_CmdHist *prev;
	struct	SDS_CmdHist *next;
};


struct SDS_dragvars {
	int 		   mode;
	int 		   applyortho;
	int 		   enternub;
	int 		   gotnub;
	int 		   it;
	int 		   firstdrag;
	int 		   color;
	int 		   dashmode;
	int 		   cursor;
	int 		   breakout;
	bool		   numok;
	sds_matrix	   matx;
	sds_name	   nmSelSet;
	sds_point	   pt1, pt2, pt3, OrthoPt, LastDrag;
	sds_real	   ang;
	sds_real	   nub;
	sds_real	   scrht;
	sds_point	   xfa[4];
	sds_point	   extru;
  sds_real		 dang;
	double *elpt;
	db_handitem *elp;
	db_drawing *flp;
	struct resbuf *vects;
  int (*scnf) (sds_point pt, sds_matrix mt) ;
	struct resbuf *rblst;
};

struct SDS_BinChange {
	void *where;
	void *data;
	int   len;
	struct SDS_BinChange *next;
};

struct SDS_prevview {
	sds_point viewctr;		//center point in UCS coordinates (not necessarily at current elev)
	//NOTE:  If perspective view is active, viewctr will contain the TARGET instead of viewctr
	sds_real  viewsize;		//size of screen in projection plane, in dwg units
	sds_point viewdir;		//direction of view (TOWARD camera from either TARGET or VIEWCTR)
	int	  viewmode;			//mode used for viewing (Ortho, Perspective, Clipping, etc.)
	sds_real  twist;		//twist for this view
	sds_real  frontz;		//front clipping dist
	sds_real  backz;		//back clipping dist
	sds_real  prjelev;		//elevation used in projecting viewctr(or target) onto projection plane
	struct SDS_prevview *prev;
	struct SDS_prevview *next;
};

//BugZilla No. 78155; 27-05-2002 [
struct cmd_dimlastpt {

	/********************************************************************************
	 * Author:	Dmitry Gavrilov.
	 * Purpose:	Safe initialization constructor.
	 * Returns:	None.
	 ********************************************************************************/
	cmd_dimlastpt()
	{
		ename[0] = ename[1] = 0L;
		r50 = r52 = elev = pt10[0] = pt10[1] = pt10[2] = 0.0;
		DB_PTCPY(pt13, pt10);
		DB_PTCPY(pt14, pt10);
		DB_PTCPY(pt15, pt10);
		DB_PTCPY(pt16, pt10);
		DB_PTCPY(pt210, pt10);
		DB_PTCPY(startpt, pt10);
		DB_PTCPY(startptother, pt10);
		DB_PTCPY(vertex, pt10);
		DB_PTCPY(ucsaxis[0], pt10);
		DB_PTCPY(ucsaxis[1], pt10);
		DB_PTCPY(ucsaxis[2], pt10);
		DB_PTCPY(ucsorg, pt10);
		pt210[2] = ucsaxis[0][0] = ucsaxis[1][1] = ucsaxis[2][2] = 1.0;
	}

	sds_name  ename;
	sds_real  r50,
			  r52;
	int 	  i70;
	sds_point pt10,
			  pt13,
			  pt14,
			  pt15,
			  pt16,
			  pt210,
			  startpt,
			  startptother,
			  vertex;
	sds_point ucsaxis[3],
			  ucsorg;
	sds_real  elev;
};
//BugZilla No. 78155; 27-05-2002 ]

//** Protos

class CIcadDoc;
class CIcadView;
class db_handitem;
class CDrawDevice;

int			   sds_pmtssget(const char *szSelMsg,const char *szSelMethod, void *pFirstPoint, const void *pSecondPoint,
							const struct sds_resbuf *prbFilter, sds_name nmNewSet, const int OmitFromPrevSS,
							bool bIncludeInvisible=true, bool bIncludeLockedLayers = false,
							bool bDirectCall = true /* add [ */,bool bsetPrevSS = false /* ]*/); //EBATECH(FUTA)

int			   SDS_SetActiveVPbyNum(int VPnum);
int 		   SDS_InitThisView(CIcadView *pView);
int			   SDS_CopyEntLink(db_handitem **dest,db_handitem *hip);
int 		   SDS_CompEntLinks(db_BinChange **chglst, db_handitem *oldhip,db_handitem *newhip);
int 		   SDS_VPeedToView(db_drawing *flp,db_handitem *elp,struct gr_view **gViewVP,CIcadView *pView);
int			   SDS_SetClipInDC(CIcadView* pView, db_handitem* pVPort, bool bClearOnly);
int 		   SDS_GetVarSimple(short qidx, struct resbuf *res);
int 		   SDS_GetPreviewBmp(const char* fileName, void** pHBITMAP, unsigned long* pAllocatedBytes, short* bIsBitmap);
int 		   SDS_getvar(const char *vname, short qidx, struct resbuf *res, db_drawing *dp, db_charbuflink *configsv, db_charbuflink *sessionsv);
int 		   SDS_setvar(const char *vname, short qidx, const struct resbuf *sour, db_drawing *dp, db_charbuflink *configsv, db_charbuflink *sessionsv, short asis);
struct resbuf *SDS_tblgetter(const char *tabname, const char *recname, short setrec, db_drawing *dp);
struct resbuf *SDS_tblgetter2(const char *tabname, const char *recname, short setrec, db_drawing *dp);
int 		   SDS_DrawLine(const sds_point from, const sds_point to, int color, int hl, int xor, db_drawing *dp, int BitBlt2Scr);
int			   SDS_RedrawEntity(const sds_name ent, int mode, CIcadView *arg_pView,CIcadDoc *pDoc, int BitBlt2Scr );
int			   SDS_RedrawDrawing( db_drawing *flp, CIcadView *arg_pView,CIcadDoc *pDoc,int BitBlt2Scr);
int			   SDS_BuildRegenList(db_drawing *flp,struct gr_view *view,CIcadView *pView,CIcadDoc *pDoc);
int SDS_SaveDataForPreviousOrUndo( CIcadView *pView, db_drawing *flp, int tilemode, int cvport );
int SDS_RedrawAfterZoom( CIcadView *pView, db_drawing *flp, int tilemode, int cvport, const sds_real *viewsize );
int 		   SDS_ZoomIt(db_drawing *dp,int mode, sds_point center, const sds_real *viewsize,const int *viewmode, sds_point viewdir, const sds_real *twistorfrontz, const sds_real *backz);
struct resbuf *SDS_SSToVects(const sds_name ss, db_drawing *flp,struct gr_view *view);
int 	   SDS_DrawFill(const sds_point *pts, int npts, int color, int hl, int xor, db_drawing *dp, int BitBlt2Scr);
int 		   SDS_VarToTab(db_drawing *dp,db_handitem *hip);
int			   SDS_TabToVar(db_drawing *dp,db_handitem *hip);
CBitmap		  *SDS_DrawBitmap(db_drawing *dp,char *Fname,const char *Bname,db_handitem *Ename,int cx,int cy,BOOL bFill);
void		   SDS_FreeUndoList(void *);
int 		   SDS_UndoGroup(db_drawing *dp, int nGroup);
int 		   SDS_RedoGroup(db_drawing *dp);
int			   SDS_UndoBack(db_drawing *dp);
int			   SDS_UndoDisplay(db_drawing *dp);
int 		   SDS_SetUndo(int mode,void *data1,void *data2,void *data3,db_drawing *dp);
int			   SDS_entmake(const struct sds_resbuf *prbEntList,db_drawing *argflp);
int 		   SDS_entmakeImageCopy(struct sds_resbuf* pEntityList);
int 		   SDS_entmakeImageInsert(struct sds_resbuf* pEntityList, db_drawing* pDrawing);
int 		   SDS_updateMLine(sds_name ename, sds_name newename);
int			   SDS_ViewToVars2Use(CIcadView *pView,db_drawing *dp,struct gr_viewvars  *viewvarsp);
void		   SDS_DrawEntity(db_handitem *elp,CDC *cdc,db_drawing *flp,CIcadView *pView);
HPALETTE	   SDS_GetHPalette(void);
CPalette	  *SDS_GetNewPalette(void);
int			   SDS_BroadcastRQToSDSApps(int RQcode);
void		   SDS_CancelAllPending(int NoMenu);
int			   SDS_AutoLoad(void);
CBitmap 	  *SDS_DimBitmap(int cx,int cy,int mode);
int 		   SDS_xforment(sds_name ename, struct resbuf *argelist, sds_matrix genmat);
int SDS_simplexforment( sds_name ename, struct resbuf *argelist, sds_matrix genmat );

int 		   SDS_WriteAlias(char *Fname);
int 		   SDS_DefaultAlias(void);
int 		   SDS_FreeAlias(void);
int 		   SDS_ReadAlias(char *Fname);
int		   SDS_ReadAccelerators(char* Fname);

int 	   SDS_dragobj_cb(sds_point pt3, sds_matrix mt);
int 	   SDS_dragone(sds_point pt3, int mode, int dragit, int ortho, sds_real snapang, int snapstyl);
int 		   SDS_UpdateEntDisp(const sds_name ename,int pushext,gr_view *view2use=NULL);
int 		   SDS_EntNodeDrag(CIcadDoc  *pDoc, sds_name ename, sds_point pt);
void		   SDS_FreeNodeList(CIcadDoc  *pDoc);
int 		   SDS_AddOneNode(CIcadDoc	*pDoc, sds_name ename, sds_point pt, int addtolist);
int 		   SDS_AddGripNodes(CIcadDoc  *pDoc, sds_name ename, int mode);
//4M Item:28->
int 		   SDS_DrawGripNodes(CIcadDoc  *pDoc);
//<-4M Item:28
void	   SDS_DrawArc(int color, int hl, int mode, sds_real viewht,sds_real r0,sds_real r1,sds_real r2,sds_real r3,sds_real r4,sds_real elev);
int			   SDS_PromptMenu(int Mode);
int			   SDS_BitBlt2Scr(int OnlyRect);
int 		   SDS_dwgrwtester(void);
int 		   SDS_InitLisp(void);
int 		   SDS_dragobject(int mode, int dragit, const sds_point pt1, const sds_point pt2, const sds_real ang, LPCTSTR prompt, struct resbuf **retrb, sds_point retpt, char *kword);
struct resbuf *SDS_ResBufCopy(struct resbuf *source);
int 		   SDS_WaitLoop(void);
void		   SDS_cmdthread( void );
int 		   SDS_GetGlobals(char *appname,HWND *hwnd,HINSTANCE *hInstance);
struct resbuf *SDS_MnuStrToRB(char *mnustr);

void			SDS_StartDraggingSS(sds_point Pt);
void			SDS_EndDraggingSS(sds_point Pt, bool IsCancel = false);


int SDS_PenColorFromACADColor( int aColor );
int SDS_BrushColorFromACADColor( int aColor );
int SDS_XORBrushColorFromACADColor( int color );
int	SDS_XORPenColorFromACADColor( int color );

int SDS_RGBFromACADColor( int aColor );
int SDS_RGB16FromACADColor( int aColor );

RGBQUAD			SDS_GetPaletteColorsRGBQUAD( int color );
int				SDS_GetPaletteColorsRGB( int color );



void		   SDS_SetLastPrompt(const char *prompt);
int 		   SDS_FreeEventList(int NoMenu);
int 		   SDS_DoOneCommand(char *cmd, int pushlsp);
int 		   SDS_ViewDir(sds_point pt1);
struct resbuf *SDS_EntListToVects(const struct resbuf *elist);
struct resbuf *SDS_ArcSegments(int mode, sds_real viewht,sds_real r0,sds_real r1,sds_real r2,sds_real r3,sds_real r4,sds_real elev, struct resbuf *ecsp, struct resbuf *destcsp);
void		   SDS_SyncSysVars(void);
int 		   SDS_CommandSize(HWND,int);
int 		   SDS_CommandSend(HWND,char *,int);
int			   SDS_DBModified( DWORD whichFlag);
int 		   SDS_EventMask(UINT);
int 		   SDS_Menu(HWND,char *);
int 		   SDS_Message(HWND,char *,int);
int 		   SDS_SetCursor(int);
int			   SDS_GetPickCursor();
int			   SDS_Init(HWND,LPARAM);
void		   SDS_Run();
int			   SDS_Exit( void );
int 		   SDS_ProcessInputEvent( InputEvent *pEvent );
int			   SDS_CmdLineSize(int mode);
int 		   SDS_PrintOnStatus(int box, LPCTSTR ptext, int hl);
int 		   SDS_SendMessage(int msg, WPARAM nFlags,LPARAM lParam);
int 		   SDS_SaveBitmapToBuffer(CBitmap *bitmap, char **ppBuffer, long *bytes,bool ChgBackgnd);
int			   SDS_SaveBufferToFile(char *pBuffer,long len, LPTSTR pszFile);
int			   SDS_GetColorDialog(int defcol, int *retcol, int mode);
int 		   SDS_DrawCursor(CPoint point, int curtype,CIcadView *pView);
int 		   SDS_rpextents(const sds_point extmin,const sds_point extmax,sds_point viewll, sds_point viewur,gr_view *view2use);
void		   SDS_GetViewScrollInfo(int *bposx,int *bposy,int *bsizx,int *bsizy);
void		   SDS_OnFirstView(CIcadView *pView,int UseFirstView);
int			   SDS_BitBlt2View(int OnlyRect,CIcadView *pView);
int			   SDS_GetFiled(const char *szTitle, const char *szDefaultPath, const char *szExtension, int bsOptions, struct sds_resbuf *prbFileName, const char* lpTemplateName, void(*pOnOkCallback)(HWND));
int			   SDS_StartTblRead(const char *tabname);
int			   SDS_TblReadHasMore(void);
char		  *SDS_TblReadString(void);
void		   SDS_CreateOurColorMap(void);
int			   SDS_progxformss(const sds_name nmSetName, sds_matrix mxTransform,int useprogress);
int			   SDS_ProgressStart(void);
int 		   SDS_ProgressStop(void);
int 		   SDS_ProgressPercent(int iPercentDone);
CBitmap 	  *SDS_DrawDiskFont(int cx,int cy,char *fname,char *bfname);
BOOL		   SDS_ReadFileIntoBuffer(char *pszFile,char **ppBuffer, unsigned long *bytes);
CBitmap 	  *SDS_GetBitmapFromBuffer(CDC *cdc, char *pBuffer, long bytes);
int			   SDS_regapp(const char *szApplication,db_drawing *argflp);
int 		   SDS_GetRectForVP(CIcadView* pView, db_handitem* pVPort, int* x1,int* x2,int* y1,int* y2);
int			   SDS_ssadd(const sds_name entityToAdd, const sds_name oldSelSet, sds_name newSelSet);
long		   SDS_sscpy(sds_name ss2, sds_name ss1);
int			   SDS_ssOrder(sds_name ss, bool bAscending = true);
int			   SDS_ssUnOrder(sds_name ss);
int			   SDS_ssHasIntersection(const sds_name ss1, const sds_name ss2, sds_name ss = NULL, bool bExtractCommEnts = false);
void		   SDS_SetRegenListFlag(CIcadView *pView,CIcadDoc *pDoc);
int			   SDS_ClearViewPort(db_handitem *hip,CIcadView *pView);
// EBATECH(CNBR) -[ add optional argument
//BOOL		   SDS_OurWinExec(LPCTSTR lpszImageName, LPCTSTR lpszCommandLine);
BOOL		   SDS_OurWinExec(LPCTSTR lpszImageName, LPCTSTR lpszCommandLine, WORD wShowWindow = SW_SHOWNOACTIVATE);
// EBATECH(CNBR) ]-
// ************************
// SDS_AskForPoint
//
int			   SDS_AskForPoint( const sds_point pt,
								const char *prompt,
								sds_point result,
								bool internalCall = TRUE);

int 		   SDS_CallUserCallbackFunc(int flag,void *arg1,void *arg2,void *arg3);
void		   SDS_FontSubsMsg(char *looked4,char *found);
void		   SDS_DrawDragVectors(CIcadDoc *pDoc);
int			   SDS_getangleneg(const sds_point ptStart, const char *szAngleMsg, double *pdRadians);
int			   SDS_getorientneg(const sds_point ptStart, const char *szOrientMsg, double *pdRadians);
int			   SDS_getanglebig(const sds_point ptStart, const char *szAngleMsg, double *pdRadians);
int			   SDS_getorientbig(const sds_point ptStart, const char *szOrientMsg, double *pdRadians);
int			   SDS_angtof_convert(int mode,const char *szAngle, int nUnitType, double *pdAngle);
int			   SDS_WriteWMF(ICADWMFINFO* pWmfInfo, char* pszFileName);
// *************************************************
// SDS_CreateThread
//
// Purpose
// Mirrors the CreateThread function, but allows us to control exactly
// how it is done.	In particular, the C runtime wants us to call _beginthread
// instead of CreateThread, so now we do
//
HANDLE SDS_CreateThread( LPSECURITY_ATTRIBUTES lpThreadAttributes,
							DWORD dwStackSize, // initial thread stack size, in bytes
							LPTHREAD_START_ROUTINE lpStartAddress,	// pointer to thread function
							LPVOID lpParameter,  // argument for new thread
							DWORD dwCreationFlags, // creation flags
							LPDWORD lpThreadId	// pointer to returned thread identifier
							);

VOID SDS_ExitThread( DWORD dwExitCode  );



class SDSApplication;

int SDS_MainCommandLineThread( HWND hWnd );
int SDS_LispCommandPipelineThread( HWND hWnd );

struct SDS_XAppCommandLineThreadParams
	{
	SDSApplication *pThisApp;
	};

int SDS_XAppCommandLineThread( SDS_XAppCommandLineThreadParams *pParams );

struct SDS_XAppAppThreadParams
	{
	LPTHREAD_START_ROUTINE EntryFunc;
	SDSApplication *pThisApp;
	};
int SDS_XAppAppThread( SDS_XAppAppThreadParams *pParams );

#if defined(__cplusplus)
	}
#endif

// Outside of the extern "C" block
//
int 	   SDS_PickObjects(const char *str, const void *pt1, const sds_point pt2, const struct resbuf *filter, sds_name ss, int mode, db_drawing *dp, bool bIncludeInvisible = true, bool bSpecialImageFilter = false, bool bIncludeLockedLayers = false, bool bAddToPrevSelSet = true);
int 	   SDS_getdispobjs(db_drawing *topdp, db_handitem **p_hipp,struct gr_displayobject **p_begdopp,struct gr_displayobject **p_enddopp,sds_point *p_ucsextp,db_drawing *p_dp,struct gr_view *p_viewp,short p_mode, db_viewport *pViewportForVpLayerData = NULL, bool bMeshAcisEntities = false );	/*D.G.*/// 'true' to get mesh surface disp. objs for ACIS entities.
short		   SDS_tblmesser(struct resbuf *rbll, short mode, db_drawing *dp, bool duplicatesok=false);
bool EntityMatchesFilterList( const struct resbuf *filter, db_handitem *elp, db_drawing *flp ) ;
bool SDS_PostInputEvent( const InputEvent &theEvent );

class IcadThreadController;
IcadThreadController *IDS_GetThreadController( void );
void IDS_SignalIcadExiting( void );
bool IDS_IsIcadExiting( void );
class InputEventQueueInterface;
InputEventQueueInterface *IDS_GetInputEventQueue( void );

// returns true if the current thread is the engine thread
//
// Use to verify assumptions about threading
//
bool OnEngineThread( void );


// returns true if the current thread is the UI thread
//
// Use to verify assumptions about threading
//
bool OnUIThread( void );

// *********************
// The actions are the ICAD_WNDACTION_ defines
// at the top of icadapi.h
//
LRESULT ExecuteUIAction( int iAction, LPARAM lParam = 0 );
// same as Excute... but asynchronous
//
LRESULT	PostUIAction( int iAction, LPARAM lParam = 0 );


class CommandQueue;

CommandQueue *GetMenuQueue();
CommandQueue *GetCancelScriptQueue( void );
CommandQueue *GetScriptQueue( void );
CommandQueue *GetActiveCommandQueue( void );

// EBATECH(CNBR)
void LaunchMTEXTEditor( CString& TextString, BOOL bNew = FALSE );

int sds_delss(const sds_name ss, bool bCmdErase);

