#pragma once

#define ICAD_CUS_CREATE  WM_USER+100

LRESULT CALLBACK ICAD_Tbutton(HWND hWnd,UINT uMsg,WPARAM wParam,LPARAM lParam);
LRESULT CALLBACK ICAD_Hbutton(HWND hWnd,UINT uMsg,WPARAM wParam,LPARAM lParam);
BOOL ICAD_TUp(HWND hWnd,HDC hDC,BOOL Flag);
BOOL ICAD_TDown(HWND hWnd,HDC hDC,BOOL Flag);
BOOL ICAD_HUp(HWND hWnd,HDC hDC);
BOOL ICAD_HDown(HWND hWnd,HDC hDC);
BOOL ICAD_BorderDown(RECT Rect,HDC hDC);
BOOL ICAD_BorderUp(RECT Rect,HDC hDC);
BOOL ICAD_EraseBkGround(RECT Rect,HDC hDC);
BOOL ICAD_TAB(RECT Rect,HDC hDC);
