#include "Icad.h"
#include "IntCmds.h"
#include "lisp.h"/*DNT*/
#include "cmds.h"/*DNT*/
#include "cmdsGroup.h"
#include "cmdsInet.h"
#include "cmdsLicence.h"
#include "cmdsDim.h"
#include "cmdsAlign.h"
#include "cmdsLayout.h"
#include "cmdsDraworder.h"
#include "cmdsWBlock.h"

struct SDS_InternalCmdList SDS_pInternalCmdList[] = 
{
   {"_REPLAY"/*DNT*/		,cmd_replay 	  ,SDS_CMDBOTH	,NULL  ,CMDSTR_REPLAY },
   {"_RENDSCR"/*DNT*/		,cmd_rendscr	  ,SDS_CMDBOTH	,NULL  ,CMDSTR_RENDSCR },
   {"_REGION"/*DNT*/		,cmd_region 	  ,SDS_CMDBOTH	,NULL  ,CMDSTR_REGION },
   {"_PASTESPEC"/*DNT*/ 	,cmd_pastespec	  ,0			,NULL  ,CMDSTR_PASTESPEC },
   {"_PCXIN"/*DNT*/ 		,cmd_pcxin		  ,SDS_CMDBOTH	,NULL  ,CMDSTR_PCXIN },
   {"_OLELINKS"/*DNT*/		,cmd_olelinks	  ,0			,NULL  ,CMDSTR_OLELINKS },
   {"_XREFCLIP"/*DNT*/		,cmd_xrefclip	  ,SDS_CMDBOTH	,NULL  ,CMDSTR_XREFCLIP },
   {"_ACISIN"/*DNT*/		,cmd_acisin 	  ,SDS_CMDBOTH	,NULL  ,CMDSTR_ACISIN },
   {"_ACISOUT"/*DNT*/		,cmd_acisout	  ,SDS_CMDBOTH	,NULL  ,CMDSTR_ACISOUT },
   {"_ALIGN"/*DNT*/ 		,cmd_align		  ,SDS_CMDBOTH	,NULL  ,CMDSTR_ALIGN },
   {"_ATTREDEF"/*DNT*/		,cmd_attredef	  ,SDS_CMDBOTH	,NULL  ,CMDSTR_ATTREDEF },
   {"_BOUNDARY"/*DNT*/		,cmd_bpoly		  ,SDS_CMDACAD	,NULL  ,CMDSTR_BOUNDARY }, // modified these from SDS_CMDBOTH to SDS_CMDACAD.  I'm not sure what SDS_CMDACAD does (couldn't find any effect), but I had to remove hide. I figured leaving the ACAD portion was the safest change
   {"_-BOUNDARY"/*DNT*/ 	,cmd_dashBPoly	  ,SDS_CMDACAD	,NULL  ,CMDSTR_DASH_BOUNDARY},
   {"_COPYLINK"/*DNT*/		,cmd_copylink	  ,SDS_CMDBOTH	,NULL  ,CMDSTR_COPYLINK },
   {"_GIFIN"/*DNT*/ 		,cmd_gifin		  ,SDS_CMDBOTH	,NULL  ,CMDSTR_GIFIN },
   {"_HATCHEDIT"/*DNT*/ 	,cmd_hatchedit	  ,SDS_CMDBOTH	,NULL  ,CMDSTR_HATCHEDIT },
   {"_INTERFERE"/*DNT*/ 	,cmd_interfere	  ,SDS_CMDBOTH	,NULL  ,CMDSTR_INTERFERE },
   {"_LIGHT"/*DNT*/ 		,cmd_light		  ,0			,NULL  ,CMDSTR_LIGHT },
   {"_MASSPROP"/*DNT*/		,cmd_massprop	  ,SDS_CMDBOTH	,NULL  ,CMDSTR_MASSPROP },
   {"_MATLIB"/*DNT*/		,cmd_matlib 	  ,0			,NULL  ,CMDSTR_MATLIB },
   {"_MVSETUP"/*DNT*/		,cmd_mvsetup	  ,SDS_CMDBOTH	,NULL  ,CMDSTR_MVSETUP },
   {"_REVOLVE"/*DNT*/		,cmd_revolve	  ,SDS_CMDBOTH	,NULL  ,CMDSTR_REVOLVE },
   {"_RMAT"/*DNT*/			,cmd_rmat		  ,0			,NULL  ,CMDSTR_RMAT },
   {"_PPREF"/*DNT*/ 		,cmd_rpref		  ,SDS_CMDBOTH	,NULL  ,CMDSTR_PPREF },
   {"_SAVEIMG"/*DNT*/		,cmd_saveimg	  ,SDS_CMDBOTH	,NULL  ,CMDSTR_SAVEIMG },
   {"_SCENE"/*DNT*/ 		,cmd_scene		  ,0			,NULL  ,CMDSTR_SCENE },
   {"_SECTION"/*DNT*/		,cmd_section	  ,SDS_CMDBOTH	,NULL  ,CMDSTR_SECTION },
   {"_SHOWMAT"/*DNT*/		,cmd_showmat	  ,SDS_CMDBOTH	,NULL  ,CMDSTR_SHOWMAT },
   {"_SLICE"/*DNT*/ 		,cmd_slice		  ,SDS_CMDBOTH	,NULL  ,CMDSTR_SLICE },
   {"_SOLDRAW"/*DNT*/		,cmd_soldraw	  ,SDS_CMDBOTH	,NULL  ,CMDSTR_SOLDRAW },
   {"_SOLPROF"/*DNT*/		,cmd_solprof	  ,SDS_CMDBOTH	,NULL  ,CMDSTR_SOLPROF },
   {"_SOLVIEW"/*DNT*/		,cmd_solview	  ,SDS_CMDBOTH	,NULL  ,CMDSTR_SOLVIEW },
   {"_STLOUT"/*DNT*/		,cmd_stlout 	  ,SDS_CMDBOTH	,NULL  ,CMDSTR_STLOUT },
   {"_TIFFIN"/*DNT*/		,cmd_tiffin 	  ,SDS_CMDBOTH	,NULL  ,CMDSTR_TIFFIN },
   {"_VLCONV"/*DNT*/		,cmd_vlconv 	  ,SDS_CMDBOTH	,NULL  ,CMDSTR_VLCONV },
   {"_WMFIN"/*DNT*/ 		,cmd_wmfin		  ,SDS_CMDBOTH	,NULL  ,CMDSTR_WMFIN },
   {"_WMFOPTS"/*DNT*/		,cmd_wmfopts	  ,SDS_CMDBOTH	,NULL  ,CMDSTR_WMFOPTS },
   {"_WMFOUT"/*DNT*/		,cmd_wmfout 	  ,0			,NULL  ,CMDSTR_WMFOUT },
   {"_SETLAYER"/*DNT*/		,cmd_setlayer	  ,0			,NULL  ,CMDSTR_SETLAYER },
   {"_MATCHPROP"/*DNT*/ 	,cmd_matchprop	  ,0			,NULL  ,CMDSTR_MATCHPROP },
   {"_XPLODE"/*DNT*/		,cmd_xplode 	  ,0			,NULL  ,CMDSTR_XPLODE },
   {"_SUBTRACT"/*DNT*/		,cmd_subtract	  ,SDS_CMDBOTH	,NULL  ,CMDSTR_SUBTRACT },
   {"_UNION"/*DNT*/ 		,cmd_union		  ,SDS_CMDBOTH	,NULL  ,CMDSTR_UNION },
   {"_TOLERANCE"/*DNT*/ 	,cmd_tolerance	  ,0			,NULL  ,CMDSTR_TOLERANCE },
   {"_SYSWINDOWS"/*DNT*/	,cmd_syswindows   ,0			,NULL  ,CMDSTR_SYSWINDOWS },
   {"_SPLINEDIT"/*DNT*/ 	,cmd_splinedit	  ,SDS_CMDBOTH	,NULL  ,CMDSTR_SPLINEDIT },
   {"_SPLINE"/*DNT*/		,cmd_spline 	  ,0			,NULL  ,CMDSTR_SPLINE },
   {"_SPELL"/*DNT*/ 		,cmd_spell		  ,0			,NULL  ,CMDSTR_SPELL },
   {"_SAVEASR12"/*DNT*/ 	,cmd_saveasr12	  ,0			,NULL  ,CMDSTR_SAVEASR12 },
   {"_RENDER"/*DNT*/		,cmd_render 	  ,0			,NULL  ,CMDSTR_RENDER },
   {"_RENDERFULL"/*DNT*/	,cmd_renderfull   ,0			,NULL  ,CMDSTR_RENDERFULL },
   {"_RENDERWF"/*DNT*/		,cmd_renderwf	  ,0			,NULL  ,CMDSTR_RENDERWF },
   {"_RENDERHL"/*DNT*/		,cmd_renderhl	  ,0			,NULL  ,CMDSTR_RENDERHL },
   {"_EDITGB"/*DNT*/		,cmd_editgb 	  ,0			,NULL  ,CMDSTR_EDITGB },
   {"_ROPTIONS"/*DNT*/		,cmd_roptions	  ,0			,NULL  ,CMDSTR_ROPTIONS },
   {"_MLINE"/*DNT*/ 		,cmd_mline		  ,SDS_CMDBOTH	,NULL  ,CMDSTR_MLINE },
   {"_MLSTYLE"/*DNT*/		,cmd_mlstyle	  ,SDS_CMDBOTH	,NULL  ,CMDSTR_MLSTYLE },
   {"_MLEDIT"/*DNT*/		,cmd_mledit 	  ,SDS_CMDBOTH	,NULL  ,CMDSTR_MLEDIT },
   {"_APPLOAD"/*DNT*/		,cmd_appload	  ,0			,NULL  ,CMDSTR_APPLOAD },
   {"_ARX"/*DNT*/			,cmd_arx		  ,SDS_CMDBOTH	,NULL  ,CMDSTR_ARX },
   {"_MENULOAD"/*DNT*/		,cmd_menuload	  ,0			,NULL  ,CMDSTR_MENULOAD },
   {"_MENUUNLOAD"/*DNT*/	,cmd_menuunload   ,0			,NULL  ,CMDSTR_MENUUNLOAD },
   {"_LOGFILEOFF"/*DNT*/	,cmd_logfileoff   ,0			,NULL  ,CMDSTR_LOGFILEOFF },
   {"_LOGFILEON"/*DNT*/ 	,cmd_logfileon	  ,0			,NULL  ,CMDSTR_LOGFILEON },
   {"_INTERSECT"/*DNT*/ 	,cmd_intersect	  ,0			,NULL  ,CMDSTR_INTERSECT },
//	 {"_IMPORT"/*DNT*/		  ,cmd_import		,SDS_CMDBOTH  ,NULL  ,CMDSTR_IMPORT },
   {"_3D"/*DNT*/			,cmd_3d 		  ,0			,NULL  ,CMDSTR_3D },
   {"_3DARRAY"/*DNT*/		,cmd_3darray	  ,0			,NULL  ,CMDSTR_3DARRAY },
   {"_ABOUT"/*DNT*/ 		,cmd_about		  ,0			,NULL  ,CMDSTR_ABOUT },
   {"_APERTURE"/*DNT*/		,cmd_aperture	  ,0			,NULL  ,CMDSTR_APERTURE },
   {"_ARC"/*DNT*/			,cmd_arc		  ,0			,NULL  ,CMDSTR_ARC },
   {"_AREA"/*DNT*/			,cmd_area		  ,0			,NULL  ,CMDSTR_AREA },
   {"_ARRAY"/*DNT*/ 		,cmd_array		  ,0			,NULL  ,CMDSTR_ARRAY },
   {"_ATTDEF"/*DNT*/		,cmd_attdef 	  ,0			,NULL  ,CMDSTR_ATTDEF },
   {"_ATTDISP"/*DNT*/		,cmd_attdisp	  ,0			,NULL  ,CMDSTR_ATTDISP },
   {"_ATTEDIT"/*DNT*/		,cmd_attedit	  ,0			,NULL  ,CMDSTR_ATTEDIT },
   {"_ATTEXT"/*DNT*/		,cmd_attext 	  ,0			,NULL  ,CMDSTR_ATTEXT },
   {"_AUDIT"/*DNT*/ 		,cmd_audit		  ,0			,NULL  ,CMDSTR_AUDIT },
   {"_BASE"/*DNT*/			,cmd_base		  ,0			,NULL  ,CMDSTR_BASE },
   {"_-BHATCH"/*DNT*/		,cmd_bhatch_cmdline,	SDS_CMDBOTH	,NULL  ,CMDSTR_BHATCH }, /* Albert.Isaev.ITC[31.7.2002/19:07:16] */
   {"_BHATCH"/*DNT*/		,cmd_bhatch 	  ,SDS_CMDBOTH	,NULL  ,CMDSTR_DDBHATCH },
   {"_BLIPMODE"/*DNT*/		,cmd_blipmode	  ,0			,NULL  ,CMDSTR_BLIPMODE },
   {"_BLOCK"/*DNT*/ 		,cmd_block		  ,0			,NULL  ,CMDSTR_BLOCK },
   {"_BPOLY"/*DNT*/ 		,cmd_bpoly		  ,SDS_CMDBOTH	,NULL  ,CMDSTR_BPOLY },
   {"_BOX"/*DNT*/			,cmd_box		  ,0			,NULL  ,CMDSTR_BOX },
   {"_BMPOUT"/*DNT*/		,cmd_bmpout 	  ,0			,NULL  ,CMDSTR_BMPOUT },
   {"_BREAK"/*DNT*/ 		,cmd_break		  ,0			,NULL  ,CMDSTR_BREAK },
   {"_CAL"/*DNT*/			,cmd_cal		  ,0			,NULL  ,CMDSTR_CAL },
   {"_CHAMFER"/*DNT*/		,cmd_chamfer	  ,0			,NULL  ,CMDSTR_CHAMFER },
   {"_CHANGE"/*DNT*/		,cmd_change 	  ,0			,NULL  ,CMDSTR_CHANGE },
   {"_CHPROP"/*DNT*/		,cmd_chprop 	  ,0			,NULL  ,CMDSTR_CHPROP },
   {"_CIRCLE"/*DNT*/		,cmd_circle 	  ,0			,NULL  ,CMDSTR_CIRCLE },
   {"_CMDBAR"/*DNT*/		,cmd_cmdbar 	  ,0			,NULL  ,CMDSTR_CMDBAR },
   {"_COLOR"/*DNT*/ 		,cmd_color		  ,0			,NULL  ,CMDSTR_COLOR },
   {"_COLOUR"/*DNT*/		,cmd_color		  ,0			,NULL  ,CMDSTR_COLOUR },
   {"_COMPILE"/*DNT*/		,cmd_compile	  ,SDS_CMDBOTH	,NULL  ,CMDSTR_COMPILE },
   {"_CONE"/*DNT*/			,cmd_cone		  ,0			,NULL  ,CMDSTR_CONE },
   {"_CONFIG"/*DNT*/		,cmd_config 	  ,0			,NULL  ,CMDSTR_CONFIG },
   {"_COPY"/*DNT*/			,cmd_copy		  ,0			,NULL  ,CMDSTR_COPY },
   {"_COPYHIST"/*DNT*/		,cmd_copyhist	  ,0			,NULL  ,CMDSTR_COPYHIST },
   {"_CUSTOMIZE"/*DNT*/ 	,cmd_customize	  ,0			,NULL  ,CMDSTR_CUSTOMIZE },
   {"_CYLINDER"/*DNT*/		,cmd_cylinder	  ,0			,NULL  ,CMDSTR_CYLINDER },
   {"_DBLIST"/*DNT*/		,cmd_dblist 	  ,0			,NULL  ,CMDSTR_DBLIST },
   {"_DDAPP"/*DNT*/ 		,cmd_ddapp		  ,SDS_CMDBOTH	,NULL  ,CMDSTR_DDAPP },
   {"_DDATTDEF"/*DNT*/		,cmd_ddattdef	  ,0			,NULL  ,CMDSTR_DDATTDEF },
   {"_EXPBLOCKS"/*DNT*/ 	,cmd_ddblocks	  ,0			,NULL  ,CMDSTR_EXPBLOCKS },
   {"_EXPLTYPES"/*DNT*/ 	,cmd_ddltype	  ,0			,NULL  ,CMDSTR_EXPLTYPES },
   {"_EXPFONTS"/*DNT*/		,cmd_ddstyle	  ,0			,NULL  ,CMDSTR_EXPFONTS },
   {"_EXPORT"/*DNT*/		,cmd_export 	  ,0			,NULL  ,CMDSTR_EXPORT },
   {"_DDATTE"/*DNT*/		,cmd_ddatte 	  ,0			,NULL  ,CMDSTR_DDATTE },
   {"_DDATTEXT"/*DNT*/		,cmd_ddattext	  ,0			,NULL  ,CMDSTR_DDATTEXT },
   {"_DDCHPROP"/*DNT*/		,cmd_ddchprop	  ,0			,NULL  ,CMDSTR_DDCHPROP },
   {"_SETCOLOR"/*DNT*/		,cmd_ddcolor	  ,0			,NULL  ,CMDSTR_SETCOLOR },
   {"_DDCOLOUR"/*DNT*/		,cmd_ddcolor	  ,0			,NULL  ,CMDSTR_DDCOLOUR },
   {"_DDEDIT"/*DNT*/		,cmd_ddedit 	  ,0			,NULL  ,CMDSTR_DDEDIT },
   {"_DDEMODES"/*DNT*/		,cmd_ddemodes	  ,0			,NULL  ,CMDSTR_DDEMODES },
   {"_DDGRIPS"/*DNT*/		,cmd_ddgrips	  ,0			,NULL  ,CMDSTR_DDGRIPS },
   {"_SETDIM"/*DNT*/		,cmd_ddim		  ,0			,NULL  ,CMDSTR_SETDIM },
   {"_DDINSERT"/*DNT*/		,cmd_ddinsert	  ,0			,NULL  ,CMDSTR_DDINSERT },
   {"_EXPLAYERS"/*DNT*/ 	,cmd_ddlmodes	  ,0			,NULL  ,CMDSTR_EXPLAYERS },
   {"_EXPDIMSTYLES"/*DNT*/	,cmd_expdimsty	  ,0			,NULL  ,CMDSTR_EXPDIMSTYLES },
   {"_NEWWIZ"/*DNT*/		,cmd_ddnew		  ,0			,NULL  ,CMDSTR_NEWWIZ },
   {"_SETESNAP"/*DNT*/		,cmd_ddosnap	  ,0			,NULL  ,CMDSTR_SETESNAP },
   {"_GROUP"/*DNT*/ 		,cmd_group		  ,SDS_CMDBOTH	,NULL  ,CMDSTR_DDGROUP },
   {"_-GROUP"/*DNT*/		,cmd_group_ 	  ,SDS_CMDBOTH	,NULL  ,CMDSTR_GROUP },
   {"_DDPTYPE"/*DNT*/		,cmd_ddptype	  ,0			,NULL  ,CMDSTR_DDPTYPE },
   {"_DDRMODES"/*DNT*/		,cmd_ddrmodes	  ,0			,NULL  ,CMDSTR_DDRMODES },
   {"_DDRENAME"/*DNT*/		,cmd_ddrename	  ,0			,NULL  ,CMDSTR_DDRENAME },
   {"_ENTPROP"/*DNT*/		,cmd_ddmodify	  ,0			,NULL  ,CMDSTR_ENTPROP },
   {"_DDSELECT"/*DNT*/		,cmd_ddselect	  ,0			,NULL  ,CMDSTR_DDSELECT },
   {"_SETTINGS"/*DNT*/		,cmd_ddsetvar	  ,0			,NULL  ,CMDSTR_SETTINGS },
   {"_DDUNITS"/*DNT*/		,cmd_ddunits	  ,0			,NULL  ,CMDSTR_DDUNITS },
   {"_EXPUCS"/*DNT*/		,cmd_dducs		  ,0			,NULL  ,CMDSTR_EXPUCS },
   {"_SETUCS"/*DNT*/		,cmd_dducsp 	  ,0			,NULL  ,CMDSTR_SETUCS },
   {"_EXPVIEWS"/*DNT*/		,cmd_ddview 	  ,0			,NULL  ,CMDSTR_EXPVIEWS },
   {"_SETVPOINT"/*DNT*/ 	,cmd_ddvpoint	  ,0			,NULL  ,CMDSTR_SETVPOINT },
   {"_DELAY"/*DNT*/ 		,cmd_delay		  ,0			,NULL  ,CMDSTR_DELAY },
//	 {"_DBLINKWIZ"/*DNT*/	  ,cmd_defxlink 	,0			  ,NULL  ,CMDSTR_DBLINKWIZ },
   {"_DIMENSION"/*DNT*/ 	,cmd_dim		  ,0			,NULL  ,CMDSTR_DIMENSION },
   {"_DIM1"/*DNT*/			,cmd_dim1		  ,0			,NULL  ,CMDSTR_DIM1 },
   {"_DIMALIGNED"/*DNT*/	,cmd_dimaligned   ,0			,NULL  ,CMDSTR_DIMALIGNED },
   {"_DIMANGULAR"/*DNT*/	,cmd_dimang 	  ,0			,NULL  ,CMDSTR_DIMANGULAR },
   {"_DIMBASELINE"/*DNT*/	,cmd_dimbaseline  ,0			,NULL  ,CMDSTR_DIMBASELINE },
   {"_DIMCENTER"/*DNT*/ 	,cmd_dimcenter	  ,0			,NULL  ,CMDSTR_DIMCENTER },
   {"_DIMCONTINUE"/*DNT*/	,cmd_dimcontinue  ,0			,NULL  ,CMDSTR_DIMCONTINUE },
   {"_DIMDIAMETER"/*DNT*/	,cmd_dimdiameter  ,0			,NULL  ,CMDSTR_DIMDIAMETER },
   {"_DIMEDIT"/*DNT*/		,cmd_dimedit	  ,0			,NULL  ,CMDSTR_DIMEDIT },
   {"_DIMLINEAR"/*DNT*/ 	,cmd_dimlinear	  ,0			,NULL  ,CMDSTR_DIMLINEAR },
   {"_DIMORDINATE"/*DNT*/	,cmd_dimord 	  ,0			,NULL  ,CMDSTR_DIMORDINATE },
   {"_DIMOVERRIDE"/*DNT*/	,cmd_dimoverride  ,0			,NULL  ,CMDSTR_DIMOVERRIDE },
   {"_DIMRADIUS"/*DNT*/ 	,cmd_dimradius	  ,0			,NULL  ,CMDSTR_DIMRADIUS },
   {"_DIMSTYLE"/*DNT*/		,cmd_dimstyle	  ,0			,NULL  ,CMDSTR_DIMSTYLE },
   {"_DIMTEDIT"/*DNT*/		,cmd_dimtedit	  ,0			,NULL  ,CMDSTR_DIMTEDIT },
   {"_DISH"/*DNT*/			,cmd_dish		  ,0			,NULL  ,CMDSTR_DISH },
   {"_DIST"/*DNT*/			,cmd_dist		  ,0			,NULL  ,CMDSTR_DIST },
   {"_DIVIDE"/*DNT*/		,cmd_divide 	  ,0			,NULL  ,CMDSTR_DIVIDE },
   {"_DOME"/*DNT*/			,cmd_dome		  ,0			,NULL  ,CMDSTR_DOME },
   {"_DONUT"/*DNT*/ 		,cmd_donut		  ,0			,NULL  ,CMDSTR_DONUT },
   {"_DOUGHNUT"/*DNT*/		,cmd_doughnut	  ,0			,NULL  ,CMDSTR_DOUGHNUT },
   {"_DRAGMODE"/*DNT*/		,cmd_dragmode	  ,0			,NULL  ,CMDSTR_DRAGMODE },
   {"_DTEXT"/*DNT*/ 		,cmd_dtext		  ,0			,NULL  ,CMDSTR_DTEXT },
   {"_DVIEW"/*DNT*/ 		,cmd_dview		  ,0			,NULL  ,CMDSTR_DVIEW },
   {"_DXBIN"/*DNT*/ 		,cmd_dxbin		  ,SDS_CMDBOTH	,NULL  ,CMDSTR_DXBIN },
   {"_DXFIN"/*DNT*/ 		,cmd_dxfin		  ,0			,NULL  ,CMDSTR_DXFIN },
   {"_DXFOUT"/*DNT*/		,cmd_dxfout 	  ,0			,NULL  ,CMDSTR_DXFOUT },
   {"_EDGE"/*DNT*/			,cmd_edge		  ,0			,NULL  ,CMDSTR_EDGE },
   {"_EDGESURF"/*DNT*/		,cmd_edgesurf	  ,0			,NULL  ,CMDSTR_EDGESURF },
   {"_BACKGROUNDS"/*DNT*/	,cmd_editgb 	  ,0			,NULL  ,CMDSTR_BACKGROUNDS },
   {"_ELEV"/*DNT*/			,cmd_elev		  ,0			,NULL  ,CMDSTR_ELEV },
   {"_ELLIPSE"/*DNT*/		,cmd_ellipse	  ,0			,NULL  ,CMDSTR_ELLIPSE },
   {"_END"/*DNT*/			,cmd_end		  ,0			,NULL  ,CMDSTR_END },
   {"_ERASE"/*DNT*/ 		,cmd_erase		  ,0			,NULL  ,CMDSTR_ERASE },
   {"_DELETE"/*DNT*/		,cmd_erase		  ,0			,NULL  ,CMDSTR_DELETE },
   {"_EXPLODE"/*DNT*/		,cmd_explode	  ,0			,NULL  ,CMDSTR_EXPLODE },
   {"_EXTEND"/*DNT*/		,cmd_extend 	  ,0			,NULL  ,CMDSTR_EXTEND },
   {"_EXTRUDE"/*DNT*/		,cmd_extrude	  ,SDS_CMDBOTH	,NULL  ,CMDSTR_EXTRUDE },
   {"_FILES"/*DNT*/ 		,cmd_files		  ,0			,NULL  ,CMDSTR_FILES },
   {"_FILL"/*DNT*/			,cmd_fill		  ,0			,NULL  ,CMDSTR_FILL },
   {"_FILLET"/*DNT*/		,cmd_fillet 	  ,0			,NULL  ,CMDSTR_FILLET },
   {"_FILMROLL"/*DNT*/		,cmd_filmroll	  ,SDS_CMDBOTH	,NULL  ,CMDSTR_FILMROLL },
   {"_FILTER"/*DNT*/		,cmd_filter 	  ,SDS_CMDBOTH	,NULL  ,CMDSTR_FILTER },
   {"_DDFILTER"/*DNT*/		,cmd_filter 	  ,SDS_CMDBOTH	,NULL  ,CMDSTR_DDFILTER },
   {"_PMTHIST"/*DNT*/		,cmd_flipscr	  ,0			,NULL  ,CMDSTR_PMTHIST },
   {"_GRAPHSCR"/*DNT*/		,cmd_graphscr	  ,0			,NULL  ,CMDSTR_GRAPHSCR },
   {"_GRID"/*DNT*/			,cmd_grid		  ,0			,NULL  ,CMDSTR_GRID },
//	 {"_GPS"/*DNT*/ 		  ,cmd_gps			,0			  ,NULL  ,CMDSTR_GPS },
   {"_HANDLES"/*DNT*/		,cmd_handles	  ,0			,NULL  ,CMDSTR_HANDLES },
   {"_HATCH"/*DNT*/ 		,cmd_hatch		  ,0			,NULL  ,CMDSTR_HATCH },
   {"_HELP"/*DNT*/			,cmd_help		  ,0			,NULL  ,CMDSTR_HELP },
   {"_?"/*DNT*/ 			,cmd_help		  ,0			,NULL  ,CMDSTR_QUESTIONMARK },
   {"_HIDE"/*DNT*/			,cmd_hide		  ,0			,NULL  ,CMDSTR_HIDE },
   {"_IDPOINT"/*DNT*/		,cmd_id 		  ,0			,NULL  ,CMDSTR_IDPOINT },
   {"_IGESIN"/*DNT*/		,cmd_igesin 	  ,SDS_CMDBOTH	,NULL  ,CMDSTR_IGESIN },
   {"_IGESOUT"/*DNT*/		,cmd_igesout	  ,SDS_CMDBOTH	,NULL  ,CMDSTR_IGESOUT },
   {"_INSERT"/*DNT*/		,cmd_insert 	  ,0			,NULL  ,CMDSTR_INSERT },
   {"_ISOPLANE"/*DNT*/		,cmd_isoplane	  ,0			,NULL  ,CMDSTR_ISOPLANE },
   {"_LAYER"/*DNT*/ 		,cmd_layer		  ,0			,NULL  ,CMDSTR_DDLAYER },
   {"_-LAYER"/*DNT*/		,cmd_layer		  ,0			,NULL  ,CMDSTR_LAYER },
   {"_LEADER"/*DNT*/		,cmd_leader 	  ,0			,NULL  ,CMDSTR_LEADER },
   {"_EDITLEN"/*DNT*/		,cmd_lengthen	  ,0			,NULL  ,CMDSTR_EDITLEN },
   {"_LIGHTING"/*DNT*/		,cmd_light		  ,0			,NULL  ,CMDSTR_LIGHTING },
   {"_LIMITS"/*DNT*/		,cmd_limits 	  ,0			,NULL  ,CMDSTR_LIMITS },
   {"_LINE"/*DNT*/			,cmd_line		  ,0			,NULL  ,CMDSTR_LINE },
//	 {"_3DLINE"/*DNT*/		  ,cmd_line 		,0			  ,NULL  ,CMDSTR_3DLINE },
   {"_LINETYPE"/*DNT*/		,cmd_linetype	  ,0			,NULL  ,CMDSTR_DDLINETYPE },
   {"_-LINETYPE"/*DNT*/ 	,cmd_linetype	  ,0			,NULL  ,CMDSTR_LINETYPE },
   {"_LIST"/*DNT*/			,cmd_list		  ,0			,NULL  ,CMDSTR_LIST },
   {"_LOAD"/*DNT*/			,cmd_load		  ,SDS_CMDBOTH	,NULL  ,CMDSTR_LOAD },
   {"_MAIL"/*DNT*/			,cmd_mail		  ,0			,NULL  ,CMDSTR_MAIL },
   {"_MEASURE"/*DNT*/		,cmd_measure	  ,0			,NULL  ,CMDSTR_MEASURE },
   {"_MENU"/*DNT*/			,cmd_menu		  ,0			,NULL  ,CMDSTR_MENU },
   {"_MINSERT"/*DNT*/		,cmd_minsert	  ,0			,NULL  ,CMDSTR_MINSERT },
   {"_MIRROR"/*DNT*/		,cmd_mirror 	  ,0			,NULL  ,CMDSTR_MIRROR },
   {"_MIRROR3D"/*DNT*/		,cmd_mirror3d	  ,0			,NULL  ,CMDSTR_MIRROR3D },
   {"_MOVE"/*DNT*/			,cmd_move		  ,0			,NULL  ,CMDSTR_MOVE },
   {"_MSNAPSHOT"/*DNT*/ 	,cmd_mslide 	  ,0			,NULL  ,CMDSTR_MSNAPSHOT },
   {"_MSPACE"/*DNT*/		,cmd_mspace 	  ,0			,NULL  ,CMDSTR_MSPACE },
   {"_MULTIPLE"/*DNT*/		,cmd_multiple	  ,0			,NULL  ,CMDSTR_MULTIPLE },
   {"_MVIEW"/*DNT*/ 		,cmd_mview		  ,0			,NULL  ,CMDSTR_MVIEW },
   {"_NEW"/*DNT*/			,cmd_new		  ,0			,NULL  ,CMDSTR_NEW },
   {"_PARALLEL"/*DNT*/		,cmd_offset 	  ,0			,NULL  ,CMDSTR_PARALLEL },
   {"_UNDELETE"/*DNT*/		,cmd_oops		  ,0			,NULL  ,CMDSTR_UNDELETE },
   {"_OPEN"/*DNT*/			,cmd_open		  ,0			,NULL  ,CMDSTR_OPEN },
   {"_OPENIMAGE"/*DNT*/ 	,cmd_openimage	  ,0			,NULL  ,CMDSTR_OPENIMAGE },
   {"_ORTHOGONAL"/*DNT*/	 ,cmd_ortho 	  ,0			,NULL  ,CMDSTR_ORTHOGONAL },
   {"_ESNAP"/*DNT*/ 		,cmd_osnap		  ,0			,NULL  ,CMDSTR_ESNAP },
   {"_PAN"/*DNT*/			,cmd_pan		  ,0			,NULL  ,CMDSTR_DDPAN },
   {"_-PAN"/*DNT*/			,cmd_pan		  ,0			,NULL  ,CMDSTR_PAN },
   {"_EDITPLINE"/*DNT*/ 	,cmd_pedit		  ,0			,NULL  ,CMDSTR_EDITPLINE },
   {"_PFACE"/*DNT*/ 		,cmd_pface		  ,0			,NULL  ,CMDSTR_PFACE },
   {"_PLAN"/*DNT*/			,cmd_plan		  ,0			,NULL  ,CMDSTR_PLAN },
   {"_POLYLINE"/*DNT*/		,cmd_pline		  ,0			,NULL  ,CMDSTR_POLYLINE },
   {"_PLOT"/*DNT*/			,cmd_plot		  ,0			,NULL  ,CMDSTR_PLOT },
   {"_POINT"/*DNT*/ 		,cmd_point		  ,0			,NULL  ,CMDSTR_POINT },
   {"_POLYGON"/*DNT*/		,cmd_polygon	  ,0			,NULL  ,CMDSTR_POLYGON },
   {"_PSDRAG"/*DNT*/		,cmd_psdrag 	  ,SDS_CMDBOTH	,NULL  ,CMDSTR_PSDRAG },
   {"_PSFILL"/*DNT*/		,cmd_psfill 	  ,SDS_CMDBOTH	,NULL  ,CMDSTR_PSFILL },
   {"_PSIN"/*DNT*/			,cmd_psin		  ,SDS_CMDBOTH	,NULL  ,CMDSTR_PSIN },
   {"_PSOUT"/*DNT*/ 		,cmd_psout		  ,SDS_CMDBOTH	,NULL  ,CMDSTR_PSOUT },
   {"_PSPACE"/*DNT*/		,cmd_pspace 	  ,0			,NULL  ,CMDSTR_PSPACE },
   {"_PURGE"/*DNT*/ 		,cmd_purge		  ,SDS_CMDBOTH	,NULL  ,CMDSTR_PURGE },
   {"_PYRAMID"/*DNT*/		,cmd_pyramid	  ,0			,NULL  ,CMDSTR_PYRAMID },
   {"_QSAVE"/*DNT*/ 		,cmd_qsave		  ,0			,NULL  ,CMDSTR_QSAVE },
   {"_QTEXT"/*DNT*/ 		,cmd_qtext		  ,0			,NULL  ,CMDSTR_QTEXT },
   {"_QUIT"/*DNT*/			,cmd_quit		  ,0			,NULL  ,CMDSTR_QUIT },
   {"_RAY"/*DNT*/			,cmd_ray		  ,0			,NULL  ,CMDSTR_RAY },
   {"_RECSCRIPT"/*DNT*/ 	,cmd_recmacro	  ,0			,NULL  ,CMDSTR_RECSCRIPT },
   {"_RECOVER"/*DNT*/		,cmd_recover	  ,0			,NULL  ,CMDSTR_RECOVER },
   {"_RECTANGLE"/*DNT*/ 	,cmd_rectang	  ,0			,NULL  ,CMDSTR_RECTANGLE },
   {"_REDEFINE"/*DNT*/		,cmd_redefine	  ,0			,NULL  ,CMDSTR_REDEFINE },
   {"_REDO"/*DNT*/			,cmd_redo		  ,0			,NULL  ,CMDSTR_REDO },
   {"_REDRAW"/*DNT*/		,cmd_redraw 	  ,0			,NULL  ,CMDSTR_REDRAW },
   {"_REDRAWALL"/*DNT*/ 	,cmd_redrawall	  ,0			,NULL  ,CMDSTR_REDRAWALL },
   {"_REGEN"/*DNT*/ 		,cmd_regen		  ,0			,NULL  ,CMDSTR_REGEN },
   {"_REGENALL"/*DNT*/		,cmd_regenall	  ,0			,NULL  ,CMDSTR_REGENALL },
   {"_REGENAUTO"/*DNT*/ 	,cmd_regenauto	  ,0			,NULL  ,CMDSTR_REGENAUTO },
   {"_REINIT"/*DNT*/		,cmd_reinit 	  ,SDS_CMDBOTH	,NULL  ,CMDSTR_REINIT },
   {"_READALIASES"/*DNT*/	,cmd_readaliases  ,SDS_CMDBOTH	,NULL  ,CMDSTR_READALIASES},
   {"_READACCELERATORS"/*DNT*/,cmd_readaccelerators ,SDS_CMDBOTH  ,NULL  ,CMDSTR_READACCELERATORS},
   {"_RENAME"/*DNT*/		,cmd_rename 	  ,0			,NULL  ,CMDSTR_RENAME },
   {"_FULLRENDER"/*DNT*/	,cmd_renderfull   ,0			,NULL  ,CMDSTR_FULLRENDER },
   {"_HLREMOVE"/*DNT*/		,cmd_renderhl	  ,0			,NULL  ,CMDSTR_HLREMOVE },
   {"_WIREFRAME"/*DNT*/ 	,cmd_renderwf	  ,0			,NULL  ,CMDSTR_WIREFRAME },
   {"_RESUME"/*DNT*/		,cmd_resume 	  ,0			,NULL  ,CMDSTR_RESUME },
   {"_REVSURF"/*DNT*/		,cmd_revsurf	  ,0			,NULL  ,CMDSTR_REVSURF },
   {"_MATERIALS"/*DNT*/ 	,cmd_rmat		  ,0			,NULL  ,CMDSTR_MATERIALS },
   {"_SETRENDER"/*DNT*/ 	,cmd_roptions	  ,0			,NULL  ,CMDSTR_SETRENDER },
   {"_ROTATE"/*DNT*/		,cmd_rotate 	  ,0			,NULL  ,CMDSTR_ROTATE },
   {"_ROTATE3D"/*DNT*/		,cmd_rotate3d	  ,0			,NULL  ,CMDSTR_ROTATE3D },
   {"_RSCRIPT"/*DNT*/		,cmd_rscript	  ,0			,NULL  ,CMDSTR_RSCRIPT },
   {"_RULESURF"/*DNT*/		,cmd_rulesurf	  ,0			,NULL  ,CMDSTR_RULESURF },
   {"_RUNFORM"/*DNT*/		,cmd_runform	  ,0			,NULL  ,CMDSTR_RUNFORM },
   {"_SAVE"/*DNT*/			,cmd_save		  ,0			,NULL  ,CMDSTR_SAVE },
   {"_SAVEAS"/*DNT*/		,cmd_saveas 	  ,0			,NULL  ,CMDSTR_SAVEAS },
   {"_SCALE"/*DNT*/ 		,cmd_scale		  ,0			,NULL  ,CMDSTR_SCALE },
   {"_SCRIPT"/*DNT*/		,cmd_script 	  ,0			,NULL  ,CMDSTR_SCRIPT },
   {"_SELECT"/*DNT*/		,cmd_select 	  ,0			,NULL  ,CMDSTR_SELECT },
   {"_SELGRIPS"/*DNT*/		,cmd_selgrips	  ,0			,NULL  ,CMDSTR_SELGRIPS },
   {"_SETVAR"/*DNT*/		,cmd_setvar 	  ,0			,NULL  ,CMDSTR_SETVAR },
   {"_SHADE"/*DNT*/ 		,cmd_shade		  ,0			,NULL  ,CMDSTR_SHADE },
   {"_SHAPE"/*DNT*/ 		,cmd_shape		  ,SDS_CMDBOTH	,NULL  ,CMDSTR_SHAPE },
   {"_FREEHAND"/*DNT*/		,cmd_sketch 	  ,0			,NULL  ,CMDSTR_FREEHAND },
   {"_SNAP"/*DNT*/			,cmd_snap		  ,0			,NULL  ,CMDSTR_SNAP },
   {"_PLANE"/*DNT*/ 		,cmd_solid		  ,0			,NULL  ,CMDSTR_PLANE },
   {"_SPHERE"/*DNT*/		,cmd_sphere 	  ,0			,NULL  ,CMDSTR_SPHERE },
   {"_SCROLLBAR"/*DNT*/		,cmd_scrlbar	  ,0			,NULL  ,CMDSTR_SCRLBAR },
   {"_STATBAR"/*DNT*/		,cmd_statbar	  ,0			,NULL  ,CMDSTR_STATBAR },
   {"_STATUS"/*DNT*/		,cmd_status 	  ,0			,NULL  ,CMDSTR_STATUS },
   {"_STOPSCRIPT"/*DNT*/	,cmd_stopmacro	  ,0			,NULL  ,CMDSTR_STOPSCRIPT },
   {"_STRETCH"/*DNT*/		,cmd_stretch	  ,0			,NULL  ,CMDSTR_STRETCH },
   {"_FONT"/*DNT*/			,cmd_style		  ,0			,NULL  ,CMDSTR_FONT },
   {"_-STYLE"/*DNT*/		,cmd_dashStyle	  ,0			,NULL  ,CMDSTR_STYLE },
   {"_TABLET"/*DNT*/		,cmd_tablet 	  ,SDS_CMDBOTH	,NULL  ,CMDSTR_TABLET },
   {"_TABSURF"/*DNT*/		,cmd_tabsurf	  ,0			,NULL  ,CMDSTR_TABSURF },
   {"_TEXT"/*DNT*/			,cmd_text		  ,0			,NULL  ,CMDSTR_TEXT },
   {"_-MTEXT"/*DNT*/		,cmd_cui_mtext	  ,0			,NULL  ,CMDSTR_MTEXT }, // EBATECH(CNBR)
   {"_MTEXT"/*DNT*/ 		,cmd_mtext		  ,0			,NULL  ,CMDSTR_DDMTEXT },
   {"_TEXTSCR"/*DNT*/		,cmd_textscr	  ,0			,NULL  ,CMDSTR_TEXTSCR },
   {"_TORUS"/*DNT*/ 		,cmd_torus		  ,0			,NULL  ,CMDSTR_TORUS },
   {"_TIME"/*DNT*/			,cmd_time		  ,0			,NULL  ,CMDSTR_TIME },
   {"_TIPOFDAY"/*DNT*/		,cmd_tipofday	  ,0			,NULL  ,CMDSTR_TIPOFDAY },
   {"_TRACE"/*DNT*/ 		,cmd_trace		  ,0			,NULL  ,CMDSTR_TRACE },
   {"_TREESTAT"/*DNT*/		,cmd_treestat	  ,SDS_CMDBOTH	,NULL  ,CMDSTR_TREESTAT },
   {"_TRIM"/*DNT*/			,cmd_trim		  ,0			,NULL  ,CMDSTR_TRIM },
   {"_U"/*DNT*/ 			,cmd_u			  ,0			,NULL  ,CMDSTR_U },
   {"_UCS"/*DNT*/			,cmd_ucs		  ,0			,NULL  ,CMDSTR_UCS },
   {"_UCSICON"/*DNT*/		,cmd_ucsicon	  ,0			,NULL  ,CMDSTR_UCSICON },
   {"_UNDEFINE"/*DNT*/		,cmd_undefine	  ,0			,NULL  ,CMDSTR_UNDEFINE },
   {"_UNDO"/*DNT*/			,cmd_undo		  ,0			,NULL  ,CMDSTR_UNDO },
   {"_UNITS"/*DNT*/ 		,cmd_units		  ,0			,NULL  ,CMDSTR_UNITS },
   {"_VIEW"/*DNT*/			,cmd_view		  ,0			,NULL  ,CMDSTR_VIEW },
   {"_VIEWCTL"/*DNT*/		,cmd_viewctl	  ,0			,NULL  ,CMDSTR_VIEWCTL },
   {"_VIEWPORTS"/*DNT*/ 	,cmd_viewports	  ,0			,NULL  ,CMDSTR_VIEWPORTS },
   {"_VPORTS"/*DNT*/		,cmd_viewports	  ,0			,NULL  ,CMDSTR_VPORTS },
   {"_VIEWRES"/*DNT*/		,cmd_viewres	  ,0			,NULL  ,CMDSTR_VIEWRES },
   {"_VPLAYER"/*DNT*/		,cmd_vplayer	  ,SDS_CMDACAD	,NULL  ,CMDSTR_VPLAYER },
   {"_VIEWPOINT"/*DNT*/ 	,cmd_vpoint 	  ,0			,NULL  ,CMDSTR_VIEWPOINT },
   {"_VSNAPSHOT"/*DNT*/ 	,cmd_vslide 	  ,0			,NULL  ,CMDSTR_VSNAPSHOT },
   {"_WBLOCK"/*DNT*/		,cmd_wblock 	  ,0			,NULL  ,CMDSTR_WBLOCK },
   {"_WEDGE"/*DNT*/ 		,cmd_wedge		  ,0			,NULL  ,CMDSTR_WEDGE },
   {"_XBIND"/*DNT*/ 		,cmd_xbind		  ,0			,NULL  ,CMDSTR_XBIND },
   {"_XREF"/*DNT*/			,cmd_xref		  ,0			,NULL  ,CMDSTR_DDXREF },
   {"_-XREF"/*DNT*/ 		,cmd_xref		  ,0			,NULL  ,CMDSTR_XREF },
   {"_ZOOM"/*DNT*/			,cmd_zoom		  ,0			,NULL  ,CMDSTR_ZOOM },
   {"_FACE"/*DNT*/			,cmd_3dface 	  ,0			,NULL  ,CMDSTR_FACE },
   {"_MESH"/*DNT*/			,cmd_3dmesh 	  ,0			,NULL  ,CMDSTR_MESH },
   {"_3DPOLY"/*DNT*/		,cmd_3dpoly 	  ,0			,NULL  ,CMDSTR_3DPOLY },
   {"_TOOLBAR"/*DNT*/		,cmd_toolbar	  ,0			,NULL  ,CMDSTR_DDTOOLBAR },
   {"_-TOOLBAR"/*DNT*/		,cmd_toolbar	  ,0			,NULL  ,CMDSTR_TOOLBAR },
   {"_TBCONFIG"/*DNT*/		,cmd_tbconfig	  ,0			,NULL  ,CMDSTR_TBCONFIG },
   {"_CLOSE"/*DNT*/ 		,cmd_close		  ,0			,NULL  ,CMDSTR_CLOSE },
   {"_SAVEALL"/*DNT*/		,cmd_saveall	  ,0			,NULL  ,CMDSTR_SAVEALL },
   {"_PRINT"/*DNT*/ 		,cmd_print		  ,0			,NULL  ,CMDSTR_PRINT },
   {"_PSETUP"/*DNT*/		,cmd_psetup 	  ,0			,NULL  ,CMDSTR_PSETUP },
   {"_PPREVIEW"/*DNT*/		,cmd_ppreview	  ,0			,NULL  ,CMDSTR_PPREVIEW },
   {"_WSPLIT"/*DNT*/		,cmd_wsplit 	  ,0			,NULL  ,CMDSTR_WSPLIT },
   {"_WINDOWS"/*DNT*/		,cmd_windows	  ,0			,NULL  ,CMDSTR_WINDOWS },
   {"_WCASCADE"/*DNT*/		,cmd_wcascade	  ,0			,NULL  ,CMDSTR_WCASCADE },
   {"_WCLOSEALL"/*DNT*/ 	,cmd_wcloseall	  ,0			,NULL  ,CMDSTR_WCLOSEALL },
   {"_WIARRANGE"/*DNT*/ 	,cmd_wiarange	  ,0			,NULL  ,CMDSTR_WIARRANGE },
   {"_WHTILE"/*DNT*/		,cmd_whtile 	  ,0			,NULL  ,CMDSTR_WHTILE },
   {"_WVTILE"/*DNT*/		,cmd_wvtile 	  ,0			,NULL  ,CMDSTR_WVTILE },
   {"_WOPEN"/*DNT*/ 		,cmd_wopen		  ,0			,NULL  ,CMDSTR_WOPEN },
   {"_WCLOSE"/*DNT*/		,cmd_wclose 	  ,0			,NULL  ,CMDSTR_WCLOSE },
   {"_INFLINE"/*DNT*/		,cmd_xline		  ,0			,NULL  ,CMDSTR_INFLINE },
   {"_EXIT"/*DNT*/			,cmd_exit		  ,0			,NULL  ,CMDSTR_EXIT },
   {"_NONE"/*DNT*/			,cmd_none		  ,0			,NULL  ,CMDSTR_NONE },
   {"_NEAREST"/*DNT*/		,cmd_nearest	  ,0			,NULL  ,CMDSTR_NEAREST },
   {"_ENDPOINT"/*DNT*/		,cmd_endpoint	  ,0			,NULL  ,CMDSTR_ENDPOINT },
   {"_MIDPOINT"/*DNT*/		,cmd_midpoint	  ,0			,NULL  ,CMDSTR_MIDPOINT },
   {"_CENTER"/*DNT*/		,cmd_center 	  ,0			,NULL  ,CMDSTR_CENTER },
   {"_INTERSECTION"/*DNT*/	,cmd_intersection ,0			,NULL  ,CMDSTR_INTERSECTION },
   {"_3DINTERSECTION"/*DNT*/,cmd_3dintersection,0			,NULL  ,CMDSTR_3DINTERSECTION },
   {"_2DINTERSECTION"/*DNT*/,cmd_2dintersection,0			,NULL  ,CMDSTR_2DINTERSECTION },
   {"_PLANVIEWINT"/*DNT*/	,cmd_planviewint  ,0			,NULL  ,CMDSTR_PLANVIEWINT	  },
   {"_PERPENDICULAR"/*DNT*/ ,cmd_perpendicular,0			,NULL  ,CMDSTR_PERPENDICULAR },
   {"_QUADRANT"/*DNT*/		,cmd_quadrant	  ,0			,NULL  ,CMDSTR_QUADRANT },
   {"_INSERTION"/*DNT*/ 	,cmd_insertion	  ,0			,NULL  ,CMDSTR_INSERTION },
   {"_VISIBLE"/*DNT*/		,cmd_visible	  ,0			,NULL  ,CMDSTR_VISIBLE },
   {"_NODE"/*DNT*/			,cmd_node		  ,0			,NULL  ,CMDSTR_NODE },
   {"_QUICK"/*DNT*/ 		,cmd_quick		  ,0			,NULL  ,CMDSTR_QUICK },
   {"_TANGENT"/*DNT*/		,cmd_tangent	  ,0			,NULL  ,CMDSTR_TANGENT },
   {"_COPYCLIP"/*DNT*/		,cmd_copyclip	  ,0			,NULL  ,CMDSTR_COPYCLIP },
   {"_PASTECLIP"/*DNT*/ 	,cmd_pasteclip	  ,0			,NULL  ,CMDSTR_PASTECLIP },
   {"_CUTCLIP"/*DNT*/		,cmd_cutclip	  ,0			,NULL  ,CMDSTR_CUTCLIP },
   {"_REASSOCAPP"/*DNT*/	,cmd_renameapp	  ,0			,NULL  ,CMDSTR_REASSOCAPP },
   {"_COPYEDATA"/*DNT*/ 	,cmd_copyedata	  ,0			,NULL  ,CMDSTR_COPYEDATA },
   {"_DELEDATA"/*DNT*/		,cmd_deledata	  ,0			,NULL  ,CMDSTR_DELEDATA },
   {"_MOVEEDATA"/*DNT*/ 	,cmd_moveedata	  ,0			,NULL  ,CMDSTR_MOVEEDATA },
   {"_INSERTOBJ"/*DNT*/ 	,cmd_insobject	  ,0			,NULL  ,CMDSTR_INSERTOBJ },
   {"_QUERY"/*DNT*/ 		,cmd_query		  ,0			,NULL  ,CMDSTR_QUERY },
   {"_OPENEXT"/*DNT*/		,cmd_extopen	  ,0			,NULL  ,CMDSTR_OPENEXT },
   {"_VBA"/*DNT*/			,cmd_vba		  ,0			,NULL  ,CMDSTR_VBA },
   {"_EDITEDATA"/*DNT*/ 	,cmd_editxdata	  ,0			,NULL  ,CMDSTR_EDITEDATA },
   {"_FLATTEN"/*DNT*/		,cmd_flatten	  ,0			,NULL  ,CMDSTR_FLATTEN },
   {"_JOIN"/*DNT*/			,cmd_join		  ,0			,NULL  ,CMDSTR_JOIN },
   {"_VBALOAD"/*DNT*/		,cmd_vbaload	  ,0			,NULL  ,CMDSTR_VBALOAD },
   {"_VBAUNLOAD"/*DNT*/ 	,cmd_vbaunload	  ,0			,NULL  ,CMDSTR_VBAUNLOAD },
   {"_VBARUN"/*DNT*/		,cmd_vbarun 	  ,0			,NULL  ,CMDSTR_VBARUN },
   {"_-VBARUN"/*DNT*/		,cmd_dashvbarun   ,0			,NULL  ,CMDSTR_DASH_VBARUN },
   {"_ADDINRUN"/*DNT*/		,cmd_addinrun	  ,0			,NULL  ,CMDSTR_ADDINRUN },
   {"_ADDINMAN"/*DNT*/		,cmd_vbaload	  ,0			,NULL  ,CMDSTR_ADDINMAN },
   {"_SECURITY"/*DNT*/		,cmd_vbasecurity  ,0			,NULL  ,CMDSTR_VBASECURITY },
   {"_COORDINATE"/*DNT*/	,cmd_coordinate   ,0			,NULL  ,CMDSTR_COORDINATE },
   {"_PMSPACE"/*DNT*/		,cmd_pmspace	  ,0			,NULL  ,CMDSTR_PMSPACE },
   {"_DIMLEADER"/*DNT*/ 	,cmd_dimleader	  ,0			,NULL  ,CMDSTR_DIMLEADER },
   {"_QPRINT"/*DNT*/		,cmd_qprint 	  ,0			,NULL  ,CMDSTR_QPRINT },
   {"_BACKGROUND"/*DNT*/	,cmd_editgb 	  ,0			,NULL  ,CMDSTR_BACKGROUND },
   {"_BROWSER"/*DNT*/		,cmd_browser	  ,0			,NULL  ,CMDSTR_BROWSER },
   {"_CONVERT"/*DNT*/		,cmd_convert	  ,0			,NULL  ,CMDSTR_CONVERT },
   {"_DRAWORDER"/*DNT*/ 	,cmd_draworder	  ,0			,NULL  ,CMDSTR_DRAWORDER },
   {"_DWFOUT"/*DNT*/		,cmd_dwfout 	  ,0			,NULL  ,CMDSTR_DWFOUT },
   {"_VMLOUT"/*DNT*/		,cmd_vmlout 	  ,0			,NULL  ,CMDSTR_VMLOUT },
   {"_FOG"/*DNT*/			,cmd_fog		  ,0			,NULL  ,CMDSTR_FOG },
   {"_IMAGEADJUST"/*DNT*/	,cmd_imageadjust  ,0			,NULL  ,CMDSTR_IMAGEADJUST },
   {"_IMAGEATTACH"/*DNT*/	,cmd_imageattach  ,0			,NULL  ,CMDSTR_IMAGEATTACH },
   {"_IMAGECLIP"/*DNT*/ 	,cmd_imageclip	  ,0			,NULL  ,CMDSTR_IMAGECLIP },
   {"_IMAGEFRAME"/*DNT*/	,cmd_imageframe   ,0			,NULL  ,CMDSTR_IMAGEFRAME },
   {"_IMAGEQUALITY"/*DNT*/	,cmd_imagequality ,0			,NULL  ,CMDSTR_IMAGEQUALITY },
   {"_LSEDIT"/*DNT*/		,cmd_lsedit 	  ,0			,NULL  ,CMDSTR_LSEDIT },
   {"_LSLIB"/*DNT*/ 		,cmd_lslib		  ,0			,NULL  ,CMDSTR_LSLIB },
   {"_LSNEW"/*DNT*/ 		,cmd_lsnew		  ,0			,NULL  ,CMDSTR_LSNEW },
   {"_SETUV"/*DNT*/ 		,cmd_setuv		  ,0			,NULL  ,CMDSTR_SETUV },
   {"_TRANSPARENCY"/*DNT*/	,cmd_transparency ,0			,NULL  ,CMDSTR_TRANSPARENCY },
   {"_RTPAN"/*DNT*/			,cmd_rtpan		  ,0			,NULL  ,CMDSTR_RTPAN },
   {"_RTZOOM"/*DNT*/   		,cmd_rtzoom		  ,0			,NULL  ,CMDSTR_RTZOOM },
   {"_RTROTX"/*DNT*/   		,cmd_rtrotx		  ,0			,NULL  ,CMDSTR_RTROTX },
   {"_RTROTY"/*DNT*/   		,cmd_rtroty		  ,0			,NULL  ,CMDSTR_RTROTY },
   {"_RTROTZ"/*DNT*/   		,cmd_rtrotz		  ,0			,NULL  ,CMDSTR_RTROTZ },
   {"_RTROT"/*DNT*/   		,cmd_rtrot		  ,0			,NULL  ,CMDSTR_RTROT },
   {"icad_colordlg"/*DNT*/	,cmd_colordlg	  ,SDS_CMDHIDE	,NULL  ,-1 },
   {"icad_helpdlg"/*DNT*/	,cmd_helpdlg	  ,SDS_CMDHIDE	,NULL  ,-1 },
   {"icad_sortlist"/*DNT*/	,cmd_sortlist	  ,SDS_CMDHIDE	,NULL  ,-1 },
   {"icad_strlsort"/*DNT*/	,cmd_sortlist	  ,SDS_CMDHIDE	,NULL  ,-1 },
   {"acad_strlsort"/*DNT*/	,cmd_sortlist	  ,SDS_CMDHIDE	,NULL  ,-1 },
   {"acad_colordlg"/*DNT*/	,cmd_colordlg	  ,SDS_CMDHIDE	,NULL  ,-1 },
   {"acad_helpdlg"/*DNT*/	,cmd_helpdlg	  ,SDS_CMDHIDE	,NULL  ,-1 },
   {"_LICENTERKEY"/*DNT*/	,cmd_licEnterKey,	0			,NULL  ,CMDSTR_LICENTERKEY },
   {"_LICPROPERTIES"/*DNT*/	,cmd_licProperties,	0			,NULL  ,CMDSTR_LICPROPERTIES },
   {"_URL"/*DNT*/			,cmd_url,			0			,NULL  ,CMDSTR_URL },
   {"_QRENDER"/*DNT*/		,cmd_qrender	  ,0			,NULL  ,CMDSTR_QRENDER },
   {"_QRENDERSET"/*DNT*/	,cmd_qroptions	  ,0			,NULL  ,CMDSTR_QRENDERSET },
   {"_DIMSTYLESET"/*DNT*/	,cmd_dimStyleSet  ,0			,NULL  ,CMDSTR_DIMSTYLESET },
   {"_PROJECTCENTER"/*DNT*/ ,cmd_projectCenter,0			,NULL  ,CMDSTR_PROJECTCENTER },
   {"_XCLIP"/*DNT*/ 		,cmd_xclip		  ,SDS_CMDBOTH	,NULL  ,CMDSTR_XCLIP },
   //Modified Cybage SBD 06/04/2001 DD/MM/YYYY
   //Reason : Mail from Surya Sarda(suryas@cadopia.com) Dated 03/04/2001 DD/MM/YYYY.
   {"_ONWEB"/*DNT*/ 		,cmd_onweb		  ,0			,NULL  ,CMDSTR_ONWEB },
   {"_HYPERLINK"/*DNT*/ 	,cmd_hyperlink	  ,SDS_CMDBOTH	,NULL  ,CMDSTR_HYPERLINK },
   {"_-HYPERLINK"/*DNT*/	,cmd_hyperlink_   ,SDS_CMDBOTH	,NULL  ,CMDSTR_HYPERLINK_ },
   {"_HYPERLINKOPTIONS"/*DNT*/,cmd_hyperlinkoptions,SDS_CMDBOTH  ,NULL	,CMDSTR_HYPERLINKOPTIONS },
   {"_3DCONVERT"/*DNT*/ 	,cmd_3dconvert	  ,0			,NULL  ,CMDSTR_3DCONVERT },
   //EBATECH(CNBR) 2001-06-16
   {"_DWGCODEPAGE"/*DNT*/	,cmd_dwgcodepage,	0			,NULL  ,CMDSTR_DWGCODEPAGE },
   //<alm>
   {"_SOLIDEDIT"/*DNT*/ 	,cmd_solidedit	  ,0			,NULL  ,CMDSTR_SOLIDEDIT },
   {"_COMMANDS"/*DNT*/		,cmd_commands	  ,0			,NULL  ,CMDSTR_COMMANDS },

   {"_AI_BOX"/*DNT*/		,cmd_box_mesh		,0			,NULL	,CMDSTR_AIBOX		},
   {"_AI_CONE"/*DNT*/		,cmd_cone_mesh		,0			,NULL	,CMDSTR_AICONE	},
   {"_AI_DISH"/*DNT*/		,cmd_dish_mesh		,0			,NULL	,CMDSTR_AIDISH	},
   {"_AI_DOME"/*DNT*/		,cmd_dome_mesh		,0			,NULL	,CMDSTR_AIDOME	},
   {"_AI_PYRAMID"/*DNT*/	,cmd_pyramid_mesh	,0			,NULL	,CMDSTR_AIPYRAMID	},
   {"_AI_SPHERE"/*DNT*/		,cmd_sphere_mesh	,0			,NULL	,CMDSTR_AISPHERE	},
   {"_AI_TORUS"/*DNT*/		,cmd_torus_mesh		,0			,NULL	,CMDSTR_AITORUS	},
   {"_AI_WEDGE"/*DNT*/		,cmd_wedge_mesh		,0			,NULL	,CMDSTR_AIWEDGE },
   {"_AI_CYLINDER"/*DNT*/	,cmd_cylinder_mesh	,0			,NULL	,CMDSTR_AICYLINDER },
   //</alm>
   {"_AI_REVSURF"/*DNT*/	,cmd_revsurf_mesh	,0			,NULL  ,CMDSTR_AIREVSURF },
   {"_AI_TABSURF"/*DNT*/	,cmd_tabsurf_mesh	,0			,NULL  ,CMDSTR_AITABSURF },
   {"_AI_RULESURF"/*DNT*/	,cmd_rulesurf_mesh  ,0			,NULL  ,CMDSTR_AIRULESURF },
   {"_AI_EDGESURF"/*DNT*/	,cmd_edgesurf_mesh  ,0			,NULL  ,CMDSTR_AIEDGESURF },

   {"_LAYOUT"/*DNT*/ 		,cmd_layout			,SDS_CMDBOTH,NULL	,CMDSTR_LAYOUT },
   {"_PAGESETUP"/*DNT*/ 	,cmd_pagesetup		,SDS_CMDBOTH,NULL	,CMDSTR_PAGESETUP },
   {"_LAYOUTWIZARD"/*DNT*/ 	,cmd_layoutwizard	,SDS_CMDBOTH,NULL	,CMDSTR_LAYOUTWIZARD },

   // LWEIGHT command.
   {"_LWEIGHT"/*DNT*/ 		,cmd_lweight	,0	,NULL	,CMDSTR_LWEIGHT },
   {"_LINEWEIGHT"/*DNT*/ 	,cmd_lweight	,0	,NULL	,CMDSTR_LINEWEIGHT },

   //Bugzilla::78503; 28-04-03
#ifdef BUILD_WITH_RASTER_SUPPORT
   {"_IEHELP"/*DNT*/ 	,cmd_ieHelp		,SDS_CMDBOTH,NULL	,CMDSTR_IEHELP},
#endif
};

int SDS_nInternalCmdList=sizeof(SDS_pInternalCmdList)/sizeof(SDS_pInternalCmdList[0]);

static int regInternalFunc(const char* pLocalName, void* pFunccall, const char* pGlobalName, int id) 
{
	struct resbuf rb, *tmpPtr = NULL;
	int err = RTNORM;

	// Here we'll get some double duty out of this rb by tacking on the
	// localized command name to the buffer we pass to lsp_defatom. The
	// tmpPtr is used because the call to lsp_defatom() will set rb.rbnext
	// to NULL and continue processing as usuall. We use tmpPtr to clean
	// up after ourselves.
	rb.restype = LSP_RTSUBR;
	rb.resval.rstring = (char*)pFunccall;
	rb.rbnext = NULL;
	if (id == -3)
	{
		tmpPtr = rb.rbnext = sds_newrb(RTSTR);
		rb.rbnext->resval.rstring = (char*)pGlobalName;
		rb.rbnext->rbnext = NULL;
	}
	if(lsp_defatom(pLocalName, id, &rb, 0) != 0)
		err = RTERROR;

	if (id == -3) 
	{
		tmpPtr->resval.rstring = NULL;
		sds_relrb(tmpPtr);
	}
	return err;
}

int SDS_loadfuncs() 
{
	CString tmpCmd;
	for(int i = 0; i < SDS_nInternalCmdList; i++)
	{
		tmpCmd.LoadString(SDS_pInternalCmdList[i].cmdIndex);
		if (tmpCmd.GetLength() == 0)
		{
			// Some of the commands like icad_colordlg and icad_helpdlg
			// have no localized name.
			if(!regInternalFunc(SDS_pInternalCmdList[i].globalName, SDS_pInternalCmdList[i].funcPtr, SDS_pInternalCmdList[i].globalName, -1))
				return -1;
		} 
		else
		{
			if (SDS_pInternalCmdList[i].localName == NULL) 
			{
				SDS_pInternalCmdList[i].localName = new char [tmpCmd.GetLength() + 1];
				strcpy(SDS_pInternalCmdList[i].localName, LPCTSTR(tmpCmd));
			}
			if(!regInternalFunc( SDS_pInternalCmdList[i].localName, SDS_pInternalCmdList[i].funcPtr,SDS_pInternalCmdList[i].globalName, -3))
				return -1;
		}
	}
	return 0;
}

int SDS_Unloadfuncs() 
{
	for(int i = 0; i < SDS_nInternalCmdList; i++)
	{
		IC_FREE(SDS_pInternalCmdList[i].localName);
		SDS_pInternalCmdList[i].localName = NULL;
	}
	return RTNORM;
}


